### ISSUE TITLE
docker部署不支持mysql自定义用户和密码吗

### ISSUE THREAD

**Issue by Jwrong** [brookshi/Hitchhiker#1]
docker部署不支持mysql自定义用户和密码吗

**Comment by brookshi** [comment]
应该是可以的，连数据库时会优先找这几个环境变量：
HITCHHIKER_DB_HOST
HITCHHIKER_DB_PORT
HITCHHIKER_DB_USERNAME
MYSQL_DATABASE
MYSQL_ROOT_PASSWORD
所以只需要改下 docker-compose.yml 文件，在hitchhiker的container里加上env:
HITCHHIKER_DB_USERNAM以及MYSQL_ROOT_PASSWORD就可以了

**Comment by Jwrong** [comment]
ok

**Comment by brookshi** [comment]
对了，mysql的container也得改下

**Comment by Jwrong** [comment]
我有自己的数据库，不用再启动一个了，我去试试不用compose

**Comment by Jwrong** [comment]
有HITCHHIKER_DB_PASSWORD吗

**Comment by brookshi** [comment]
用的是这个 `MYSQL_ROOT_PASSWORD`， 因为想到可能会和mysql装一起，mysql用的这个

**Comment by Jwrong** [comment]
貌似不行，启动的时候，直接使用root去连的HITCHHIKER_DB_USERNAM这个好像不起作用

**Comment by brookshi** [comment]
HITCHHIKER_DB_USERNAM 少了一个`E`，而且这个是name哦，也就是root，数据库的话是`MYSQL_DATABASE`

**Comment by brookshi** [comment]
加些说明
```
HITCHHIKER_DB_HOST               DB的host
HITCHHIKER_DB_PORT                DB的端口
MYSQL_DATABASE                      DB数据库的名字
HITCHHIKER_DB_USERNAME      DB的user name, eg: root
MYSQL_ROOT_PASSWORD         DB的密码
```

**Comment by Jwrong** [comment]
部署好了，注册时候，TypeError: Failed to fetch

**Comment by brookshi** [comment]
可否看下控制台，把错误消息截个图我看下

**Comment by Jwrong** [comment]
docker部署的，没有控制台，我去项目里找到logs/logs_file.log文件没有什么内容

**Comment by Jwrong** [comment]
我看错了，我看下浏览器控制台

**Comment by Jwrong** [comment]
我知道了，APP_HOST没有设置

**Comment by brookshi** [comment]
对的，需要一个HITCHHIKER_APP_HOST

**Comment by Jwrong** [comment]
部署好了,post请求formdata类型，该怎么填写

**Comment by brookshi** [comment]
对form这块还不太完善，需要在header里写content-type:  multipart/form-data

**Comment by Jwrong** [comment]
那参数呢，写在body里，a=b&c=d?

**Comment by Jwrong** [comment]
字体看起来有点费劲，个人意见

**Comment by brookshi** [comment]
这个需要写在url里，也可以设置到变量里

**Comment by Jwrong** [comment]
好的，知道了，希望越来越好！

**Comment by brookshi** [comment]
是吗，用的一个程序员专用的等宽开源字体，刚开始我看得也不太习惯，不过回头再找找看有没有好些的开源字体

**Comment by brookshi** [comment]
谢谢：）

**Comment by Jwrong** [comment]
写代码倒是可以用这个字体，但是用来网站显示可能有点不大好，其实不用刻意使用字体，默认就好吧

**Comment by brookshi** [comment]
也是，大家都习惯了默认的字体，回头去掉试试看

**Comment by Jwrong** [comment]
可以close了, ：）

**Comment by brookshi** [comment]
嗯：）

**Comment by jyl4944204** [comment]
> 嗯：）

[2019-05-06 09:47:50.369] [ERROR] console -   Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL, `createDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `' at line 1


对mysql版本有要求吗，创建账户后，mysql报错
