### ISSUE TITLE
nginx代理压力测试websocket报错

### ISSUE THREAD

**Issue by a108843035** [brookshi/Hitchhiker#100]
我这边使用nginx代理之后,压力测试报错,报错图如下,请问如何解决 
![tim 20180212100501](https://user-images.githubusercontent.com/15080773/36081658-b651c246-0fdc-11e8-8fde-dee10a71ec65.jpg)
![tim 20180212100812](https://user-images.githubusercontent.com/15080773/36081659-b6863422-0fdc-11e8-9ad3-dd468e52c139.png)
![tim 20180212100835](https://user-images.githubusercontent.com/15080773/36081663-c0f15c52-0fdc-11e8-82af-074b72a96da5.png)

nginx配置如下
![tim 20180212100901](https://user-images.githubusercontent.com/15080773/36081668-d387577c-0fdc-11e8-99c6-80dd3722513f.png)

**Comment by a108843035** [comment]
找到问题了,端口配置的有问题,自己已解决

**Comment by exhui** [comment]
你问下你的docker-compose.yml是怎样的

**Comment by sdsz666** [comment]
@a108843035   麻烦分享下你的配置，我现在也遇到同样的问题了
