### ISSUE TITLE
mac下docker-compose up -d报错

### ISSUE THREAD

**Issue by zsmjluo** [brookshi/Hitchhiker#101]
ERROR: for hitchhiker-mysql  Cannot start service hitchhiker-mysql: Mounts denied: 
The path /my/hitchhiker/sqldata
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.

ERROR: for hitchhiker-mysql  Cannot start service hitchhiker-mysql: Mounts denied: 
The path /my/hitchhiker/sqldata
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.

**Comment by brookshi** [comment]
@zsmjluo 这个应该是在微信上解决了吧， 应该是mac下的root目录docker没有权限创建，需要先把根目录创建出来

**Comment by zsmjluo** [comment]
@brookshi 我把配置修改了一下，/my/hitchhiker/sqldata:/private/var/lib/mysql,然后把这个mysql目录增加了权限就OK了。

**Comment by brookshi** [comment]
好的

**Comment by MGViewer** [comment]
具体的步骤是啥,同样遇到了这个问题,看你们的解释问题解决了,但是不知道动哪里

**Comment by brookshi** [comment]
@MGViewer 就是docker-compose.yml文件里面不是有一行：/my/hitchhiker/sqldata:/var/lib/mysql，mac下my这个根目录docker没权限创建，你先手工创建出来，赋予修改权限。

**Comment by manuones** [comment]
参考这个链接已解决：http://icyleaf.com/2016/08/how-to-install-rancher-on-osx/
