### ISSUE TITLE
Schedule的Notification条件可配置化

### ISSUE THREAD

**Issue by mikuazusa** [brookshi/Hitchhiker#102]
目前整个系统应该是Schedule无论执行Success或Fail都是会调起Notification的，希望能够可配置Success/Fail才发起提醒，这样更灵活而且相当于增加了一个API接口外部监控的功能。

**Comment by brookshi** [comment]
这个是有setting可以控制的，参考： http://doc.hitchhiker-api.com/cn/installation/configuration.html 
的mailOnlyForFail， 环境变量是 HITCHHIKER_SCHEDULE_MAILFORFAIL

**Comment by mikuazusa** [comment]
谢谢，看到了，这条可以关掉了
