### ISSUE TITLE
测试报告中过滤器会导致对比报告样式错乱

### ISSUE THREAD

**Issue by mikuazusa** [brookshi/Hitchhiker#105]
Schedules开启compare后测试报告若过滤PASS:FAIL会导致Compare报告样式错乱
![bug](https://user-images.githubusercontent.com/2417904/36836664-f7bc3fa4-1d74-11e8-906b-3168b642b111.png)

**Comment by brookshi** [comment]
嗯，好的，我看一下，谢谢提出来
