### ISSUE TITLE
docker 安装好以后， 首页打开， 无法注册和登陆

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#108]
按照文档，docker安装了， 首页已经打开。
但是无法注册，无法登陆

![image](https://user-images.githubusercontent.com/1652700/37150335-53be42f6-230c-11e8-8226-cc085b41e0bf.png)
![image](https://user-images.githubusercontent.com/1652700/37150365-6dffbed8-230c-11e8-8771-6384b90a0e54.png)

**Comment by brookshi** [comment]
估计是数据库没连上，请进到数据库的容器看下表是否有创建起来

**Comment by vmvz** [comment]
@brookshi 我弄了2个VPS， 都一样， 那我进去检查看看

**Comment by vmvz** [comment]
@brookshi 感谢，已经搞定，的确是数据库问题。 我正式的找台机器装。

顺便问个问题： 可以关闭注册吗？

**Comment by brookshi** [comment]
暂时不行，有需求的话可以提个issue，这个不难实现
