### ISSUE TITLE
Environment variables are not available in Common Pre Request Script

### ISSUE THREAD

**Issue by Yerhabe** [brookshi/Hitchhiker#110]
In **Common Pre Request Script** it appears that environment variables are not available via `getEnvVariable`. Instead, the result is always `undefined`.

**Comment by brookshi** [comment]
Use `{{key}}` to get value for environment variable. 
Seem it doesn't make sense, should also support function: `getEnvVariable`.
I'll implement it later.

**Comment by Yerhabe** [comment]
Thanks! Using `{{key}}` is working as you suggested.
