### ISSUE TITLE
await does not work in Global Functions

### ISSUE THREAD

**Issue by Yerhabe** [brookshi/Hitchhiker#111]
When trying to use `await` in Global Functions (as seen [here](http://doc.hitchhiker-api.com/en/Script/API.html)), an error is raised: `ReferenceError: await is not defined`;

**Comment by brookshi** [comment]
should use Nodejs 7.6+.

**Comment by Yerhabe** [comment]
I'm using the latest docker build `v0.9` which based on [this Dockerfile](https://github.com/brookshi/Hitchhiker/blob/master/deploy/docker/Dockerfile) looks to be using `node:7.10`.

**Comment by Yerhabe** [comment]
I just double-checked in the container itself and `node -v` returns `v7.10.1`.

**Comment by brookshi** [comment]
I add a test request in www.hitchhiker-api.com, seem it works fine.
You can login with account: test@test.test, password: 123456
Request named `global function await` in collection: `New Collection`

**Comment by Yerhabe** [comment]
Thanks for that. Played with the code some more and got it working, looks like it was an issue on my end.

**Comment by brookshi** [comment]
Close issue.
You can reopen it if any question.
