### ISSUE TITLE
恳求增加Stress Test结果的细节展示功能

### ISSUE THREAD

**Issue by kanedulles** [brookshi/Hitchhiker#112]
我们发现了您开发的Hitchhiker工具，在开展API自动化和压力测试领域有非常大的优势和便利；但同时我们发现Stress Test的结果展示非常模糊。
恳求您对结果中的响应时间做一些详细的展示，例如用饼图或者柱状图显示<1秒、1~3秒、3~5秒、5~10秒、>10秒的比例。
当然，您也可以在页面中增加结果展示的设置功能，由我们来对结果进行这方面的配置操作，这样也可以降低您的编码工作。

**Comment by brookshi** [comment]
这一阶段的压测结果细节先到这里，以后考虑改进整个压测，到时再改进
