### ISSUE TITLE
部署在公网服务器中, 有办法测试本地api吗?

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#114]
postman 设置了 www.a.com 那么改hosts 都是可以测试的.
apizza 也可以这样测试.

那么我们 Hitchhiker 部署在服务器中以后,可以测试本地 127.0.0.1 api吗?

**Comment by brookshi** [comment]
postman因为是单机的，所以 没问题，apizza好像用的是chrome的插件。
#96 所以我也加了这个，可以让公网的测试本地
目前Hitchhiker在没有插件的情况下采用了另外一种办法，不过需要本地机器能被访问，在project里改个人的localhost，这样发请求时如果是localhost，会改成对应的ip.
不过这种路子貌似在你那里是不行的，一般用在局域网内。

**Comment by vmvz** [comment]
@brookshi  我清楚了, 我目前的想法是 python代码 实时 自动上传到测试服务器中, 那么可被访问.就解决了. 先这样体验一下试试了.

**Comment by brookshi** [comment]
@vmvz 直接在测试服务器里测试本地代码吗，这倒是个法子，不过不能调试了

**Comment by vmvz** [comment]
@brookshi 我找人讨论了一下, 你看看能不能先做一个事情.

简单说: Hitchhiker-mysql能够同步就好了
---
Hitchhiker是网页版的,
其实为了测试本地API,chrome插件是最完美的解决方案, postman一开始也是这样.

如果没有插件的情况下, 只能把Hitchhiker部署在局域网才能完美测试. 

问题来了!

环境1(假设公司)
局域网内部署了Hitchhiker-A, 那么就有数据库 Hitchhiker-A-mysql, 这个数据库要是能比较方便的同步(网盘,服务器,ftp等等都可以), 为的就是换了一个环境, 还能继续用.

环境2(假设家里)
局域网部署了Hitchhiker-B, 数据库Hitchhiker-B-mysql能够比较方便同步成 Hitchhiker-A-mysql, 那么也能解决 Hitchhiker不需要部署到公网的问题.

我查查mysql有没有这样类似的方案. 这有点曲折呀

**Comment by brookshi** [comment]
@vmvz 牛

**Comment by brookshi** [comment]
refer to : #96
