### ISSUE TITLE
post 发送body数据可能有bug

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#115]
打开这个任务(本地已经清空缓存了)
如果直接点击发送按钮,返回结果是错误的.
![image](https://user-images.githubusercontent.com/1652700/37237904-2ff49528-2456-11e8-8c83-8123ebffb170.png)

如果进行下面操作, 再次选择一下json,就正常了
![image](https://user-images.githubusercontent.com/1652700/37237921-6dbf86e2-2456-11e8-8d30-dd022f220b46.png)

如果用一键测试工具,发现body数据是空的

![image](https://user-images.githubusercontent.com/1652700/37237944-c085e40c-2456-11e8-9993-dd743cc3255e.png)

@brookshi 看看 post是不是有bug, 还是我哪里错了?

**Comment by brookshi** [comment]
看下header

**Comment by vmvz** [comment]
@brookshi  header 写了 json
![image](https://user-images.githubusercontent.com/1652700/37239143-f01feafe-2470-11e8-8ae0-15b4ac2bcae9.png)
