### ISSUE TITLE
轻微bug: header中收藏的key 取消收藏以后,还会提示

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#117]
解决办法:
1. 取消收藏
2. 删除这个变量via
3. 发现这样才可以,一定要删除这个变量

---
via 我已经取消收藏了
![image](https://user-images.githubusercontent.com/1652700/37238999-cacf7542-246d-11e8-9ca3-694e478b4003.png)

**Comment by vmvz** [comment]
清空缓存 退出以后,发现 取消收藏失败
![image](https://user-images.githubusercontent.com/1652700/37239007-0682217a-246e-11e8-8ffd-0fa11bf9a360.png)

**Comment by brookshi** [comment]
取消掉这个功能，因为有了common setting后这个功能意义已经不大了，参考#93
