### ISSUE TITLE
关闭标签的方法希望增强 [建议]

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#119]
目前多开几个标签以后, 太不方便了

希望能增加关闭方式,不要鼠标瞄准哪个 x 来关闭

谢谢

**Comment by vmvz** [comment]
@brookshi 我看计划是0.13 可以提前一点吗?  现在打开多了以后,要关闭真的很累人.

谢谢

**Comment by brookshi** [comment]
其实你可以不用关闭打开的标签，通过左边的选择就比较方便了

**Comment by vmvz** [comment]
![image](https://user-images.githubusercontent.com/1652700/39621100-1adf1768-4fc0-11e8-892b-86f3412c4adb.png)
可以参考的
