### ISSUE TITLE
如何添加表单数据？

### ISSUE THREAD

**Issue by qianlei90** [brookshi/Hitchhiker#12]
Postman中提供了`form-data`、`x-www-form-urlencoded`、`raw`、`binary`四种body类型，Hitchhiker中该如何设置表单呢？
![image](https://user-images.githubusercontent.com/5654791/30261822-f76b98a6-9700-11e7-9235-b33f2132fe81.png)

**Comment by brookshi** [comment]
这块功能暂时不完善，不过除了binary之外，其他都还是可以用，只是要手动添加header: `Content-Type: application/x-www-form-urlencoded`，然后body里输入表单内容，如：`a=1&b=2`，那个下拉菜单选择什么无所谓，只是会自动添加header。
后续版本会陆续加上这些类型。

**Comment by qianlei90** [comment]
好的，有解决办法就行，我先试着抛弃Postman转移到Hitchhiker上来

**Comment by brookshi** [comment]
感谢使用：），Hitchhiker会持续迭代，2周一个版本。有什么需求的话非常欢迎提出来讨论。
问下，你是打算一个人用还是team用呢

**Comment by qianlei90** [comment]
想在team中推广，他们可能会不太习惯，虽然在内网部署了但暂时也只有我一个人在试用。因为非常觊觎Postman Pro的功能，所以在找一个开源的、能自己内网部署不用上传数据到外网的一个解决方案，就在v2ex上找到了这个项目。我自己是服务端的Python web开发，如果有需要你可以提出来，我可以帮你一把，这个产品不错，希望能够快速成熟起来，我们一起加油

**Comment by brookshi** [comment]
:+1: ，加油

**Comment by 184609680** [comment]
body里输入表单内容，如：a=1&b=2
语法提示错误

**Comment by brookshi** [comment]
因为body的格式现在默认是json，所以表单内容会有提示格式 不对，请先忽视这错误，我后面会改进表单这块。

**Comment by Yerhabe** [comment]
Loving Hitchhiker but this is a real negative compared to Postman. Would be great to be able to add params with a key/value interface like when adding Headers, as well as adding x-www-form-urlencoded to the dropdown.

Keep up the good work!

**Comment by brookshi** [comment]
@Yerhabe Thanks, I'll boost priority for form supporting.

**Comment by Yerhabe** [comment]
Here's a little hack I'm using to get around it for now. 

In the **Common Pre Request Script** I convert the JSON body to urlencoded as well as setting the `Content-Type` to `application/x-www-form-urlencoded`.

So a JSON body of `{"a": 1, "b": 2}` becomes `a=1&b=2`;

```
const request = hitchhiker.request;

const body = JSON.parse(request.body);
const urlencodedArr = Object.keys(body).map(k => `${k}=${body[k]}`);
request.body = urlencodedArr.join('&');
request.headers['Content-Type'] = 'application/x-www-form-urlencoded';

hitchhiker.setRequest(request);
```

**Comment by brookshi** [comment]
@Yerhabe great! :smile: 
I often thought Hitchhiker should support plugins which could customize UI, function etc.
User could share or use these plugins directly.
