### ISSUE TITLE
多人同步问题

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#120]
已经开启同步
```
      - HITCHHIKER_SYNC_INTERVAL=5      
      - HITCHHIKER_SYNC_ONOFF=true
```

如果成员A修改了 X request, 那么成员B 需要刷新整个页面才能看到A修改的结果吗?

**Comment by brookshi** [comment]
开启了同步就不需要了，每5秒会自动刷新一次，当然A修改的需要保存，B才能看得到

**Comment by vmvz** [comment]
1. 成员B关闭X request以后, 重新打开还是没有看到修改, 需要整个网页刷新才可以. 我也觉得奇怪

2. 同步和刷新, 能否解释细一些? 刷新应该是本地刷新, 同步是不是成员之间?

**Comment by brookshi** [comment]
是不是同步没生效呢，每隔5秒上面的同步会不会转圈

**Comment by brookshi** [comment]
同步成员之间的

**Comment by vmvz** [comment]
@brookshi  如果修改内容以后,点击 save, 同步图标出现转圈, 然后立刻同步好了.

但是没有任何修改的时候, 每5秒没有转圈的情况发生.

(控制台里面 没有发现5秒一个更新的请求)

**Comment by brookshi** [comment]
那同步没生效

**Comment by vmvz** [comment]
控制台没有任何报错,  docker部署的,我应该从什么地方去查错.
我的配置文件
```conf
version: '2'
services:
  hitchhiker:
    image: registry.cn-hangzhou.aliyuncs.com/brook/hitchhiker-cn:v0.9
    container_name: hi
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
      - HITCHHIKER_APP_HOST=http://www.a.com:8888/
      - HITCHHIKER_SYNC_INTERVAL=30
      - HITCHHIKER_SYNC_ONOFF=true
# add environment variable
    ports:
```

**Comment by brookshi** [comment]
前端印象中做了个限制，5秒不行，设成30秒试试

**Comment by brookshi** [comment]
第一次多等下

**Comment by vmvz** [comment]
@brookshi 我已经是30s了`HITCHHIKER_SYNC_INTERVAL=30`, 而且每5秒自动的转圈圈一直没有出现过.

**Comment by brookshi** [comment]
这个就是间隔时间，设成30秒就是每30秒同步

**Comment by vmvz** [comment]
环境变量是boolean时，用 1 表示true, 0 表示false
应该改成HITCHHIKER_SYNC_ONOFF=1
