### ISSUE TITLE
参数为 null 的时候可以不发送到请求中吗?

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#125]
如果参数为空, 那么请求中 是不是 不要 带这个参数到服务器中?

![image](https://user-images.githubusercontent.com/1652700/37473698-a2567936-28a9-11e8-8417-1994ca91c9b4.png)

**Comment by brookshi** [comment]
id={{id}}，这个变量怎么转

**Comment by gumutianqi** [comment]
@vmvz 这种情况应该是后端处理
