### ISSUE TITLE
Schedules 结果页面 参数显示调整

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#127]
如果 Param 参数多的时候, 不会被隐藏/折叠.

希望 Param的显示方式和 headers body tests 一样, 可以自动隐藏一部分,

要不然 参数多的时候容易出现图示这样的情况.

谢谢

![image](https://user-images.githubusercontent.com/1652700/37699089-c1508450-2d20-11e8-9ed6-c1b27cd1fd5b.png)

**Comment by vmvz** [comment]
1. 希望 param可以隐藏大部分
2. 希望name不会被换行. 并且 `collection` 和 `folder` 构成name的时候能区分一下

为了方便你调试
我再截一个图给你看

![image](https://user-images.githubusercontent.com/1652700/37814720-5cefbd82-2ea6-11e8-8683-6131167ca6e8.png)

**Comment by brookshi** [comment]
其实就是param太长压缩了其他列的空间
