### ISSUE TITLE
同一个请求在postman可以返回结果，在本应用上返回错误结果

### ISSUE THREAD

**Issue by eeokee** [brookshi/Hitchhiker#13]
![image](https://user-images.githubusercontent.com/3079825/30315090-6b3751f6-97d5-11e7-9a4a-b01a75bb6e5a.png)

![image](https://user-images.githubusercontent.com/3079825/30315344-2c5fdc0e-97d6-11e7-9c88-1ebca3653d47.png)

作者你好，接口是内网，外网可能无法访问，如果需要提供更详细信息，可告诉我如何调试，我之后可把调试信息补充到此issue中

开发环境
Win10x64
Node8.1
Chrome61

**Comment by tidezyc** [comment]
这行空指针了啊，贴个代码看看
![image](https://user-images.githubusercontent.com/1592766/30316918-4ffe496a-976e-11e7-9289-11da45e63c07.png)

**Comment by brookshi** [comment]
@eeokee Hitchhiker是部署在局域网的吗

**Comment by brookshi** [comment]
可以考虑用fiddler之类的工具抓下包看看postman发出的和hitchhiker发出的有啥不一样

**Comment by brookshi** [comment]
哦，看了你的错误提示，大概知道什么原因了，可能确实是Hitchhiker的问题，因为你这个请求post的是空的是吧，可能发了个undefined出去了，我查下

**Comment by brookshi** [comment]
调试了下，body是空的话会发空字符串，不过看你请求返回来的错误来看，是这行代码的问题
![image](https://user-images.githubusercontent.com/13607728/30319049-6722d5c0-97e1-11e7-867d-96e16467ce78.png)
还是需要你用fiddler抓下包对比下看看

**Comment by tidezyc** [comment]
<img width="352" alt="screen shot 2017-09-12 at 17 23 47" src="https://user-images.githubusercontent.com/1592766/30319202-d9d9f9bc-9774-11e7-8ae6-0f6e5d8c12c9.png">
不出意外的话，很有可能是一个空value的header 触发了NullPointerException

@brookshi 空value的header应该过滤下

**Comment by brookshi** [comment]
@tidezyc 嗯，Cookie为空，是应该过滤下。
@eeokee 麻烦用tab bar右边的+号新建一个request，用同样的url,header试试看，用tab bar创建出来的不保存的话不会带cookie

**Comment by eeokee** [comment]
@tidezyc 
关于接口返回的异常，由于接口不属于我们管辖（我们没有其代码），因此暂且略过。


@brookshi 
1. 确实部署在局域网，我本机上
2. 应该和空body和cookie无关，因为我取消填写Authorization 或 Authorization 值填错误值时接口都能返回给我“正确”返回结果
![image](https://user-images.githubusercontent.com/3079825/30363124-a0beb00a-9891-11e7-899b-cff0b47a9cc6.png)
3. 新建tab访问后结果没有不同

**Comment by tidezyc** [comment]
@eeokee 因为认证失败之后就不会触发接下去的header或者body检查，所以这个不能排除 body和cookie空值的问题

**Comment by brookshi** [comment]
@eeokee @tidezyc 还有另外一个可能，服务端可能校验了一些header，比如：User-Agent，我抓了下postman发出的header，看看把这些header加进去能否解决（用Bulk Edit，直接复制进去就可以了）：
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
Cache-Control:no-cache
Content-Type:application/json
Origin:chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token:0c9ce740-22a4-70fd-6a0d-ac0296c42dab
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
```

**Comment by eeokee** [comment]
@tidezyc @brookshi  你们说得对，错误的原因很可能是postman默认会发出“常规”的header
我试着添加 Accept: */* 后问题解决
![image](https://user-images.githubusercontent.com/3079825/30365645-f5bc32ea-989a-11e7-8358-8ebe32c1a61f.png)

**Comment by brookshi** [comment]
看来我也得考虑下这个问题，是否默认发些通用的header

**Comment by tidezyc** [comment]
@brookshi 是的，ua和accept 是需要加上的，好多系统都会检查这两个header

**Comment by brookshi** [comment]
ok, 下个版本加上

**Comment by brookshi** [comment]
fixed
