### ISSUE TITLE
请求在更新日志中，加入0.9和0.10的内容变化

### ISSUE THREAD

**Issue by kanedulles** [brookshi/Hitchhiker#130]
尊敬的Brook：我们从Hitchhiker v0.8开始接触到这个工具，团队同事表示很满意。本地也更新了最近的2个版本；但由于更新日志中没有增加相应的变化，恳求您能够在百忙之中做出更新。期待着下一个版本！非常感谢！

**Comment by brookshi** [comment]
哦哦，忘了更新到在线文档了，我回头更新下， https://github.com/brookshi/Hitchhiker/blob/master/cn/change_log.md  这里也可以看。

**Comment by vmvz** [comment]
@kanedulles 你用docker部署的吗?

**Comment by kanedulles** [comment]
@vmvz : 不是。。。我是在CentOS上安装依赖软件、用Hitchhiker安装包的方法装的。
