### ISSUE TITLE
setEnvVariable 有办法保存多个结果吗?

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#134]
目标: 一个请求, 增加了5个 "商品",  这5个商品的ID 想保存起来, 用于 其他请求(更新, 删除)

目前, 只能保存一个ID, `hitchhiker.setEnvVariable('id', '101');`

如果 setEnvVariable 可以设置类似称为 list, array的方式就好了, 每次去 append.

有没有其他好办的解决方案.

**Comment by brookshi** [comment]
可以用 setEnvVariable('id', ['101'])， 后面要append可以getEnvVariable('id').push('102')

**Comment by vmvz** [comment]
@brookshi 这方法不错, 可是在` Schedules ` 的时候 好像有点问题

**Comment by vmvz** [comment]
@brookshi 如果 环境变量中有  id_list.pop() 操作以后, 在`Schedules` 后续的request中都会出错了

**Comment by brookshi** [comment]
demo 里schedule我试了下没有问题，你可以把问题在demo里用test@test.test, 123456账号写个例子重现
