### ISSUE TITLE
按操作按照后跳转出错了,node后台没有日志，大神帮忙看看呀

### ISSUE THREAD

**Issue by wangxin8899** [brookshi/Hitchhiker#135]
![image](https://user-images.githubusercontent.com/11817392/37819525-b975d282-2eb8-11e8-87be-e264b861c43b.png)

![image](https://user-images.githubusercontent.com/11817392/37819561-d73c14ac-2eb8-11e8-82a9-7b9bf78b2354.png)

**Comment by vmvz** [comment]
我没有遇到过这样问题, 再看一次文档吧

**Comment by brookshi** [comment]
@vmvz 感谢帮忙回复， 这个问题后来微信上沟通过，是数据库的版本问题

**Comment by vmvz** [comment]
@brookshi 是不是擅长用mysql,  怎么没考虑 Nosql 例如  https://github.com/ideawu/ssdb

**Comment by brookshi** [comment]
mysql相对是熟一点，mongodb是有考虑过的，不过设计时想到hitchhiker需要存的数据彼此关系还是很紧密的，所以还是决定用关系型数据库。
