### ISSUE TITLE
右上角用户菜单增加单独的 clear cache

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#136]
用了setEnvVariable, 如果有错误的时候, 如何清除里面的一些变量?

所以是不是 右上角用户菜单增加单独的 `clear cache` 按钮会方便一些?

![image](https://user-images.githubusercontent.com/1652700/37835445-22128808-2eeb-11e8-85c1-9893299775ae.png)

**Comment by brookshi** [comment]
这个clear cache清的是浏览器的cache，和变量没什么关系，清除可以用api  removeEnvVariable

**Comment by vmvz** [comment]
好的
