### ISSUE TITLE
parameters lenght显示错误

### ISSUE THREAD

**Issue by brookshi** [brookshi/Hitchhiker#138]
![image](https://user-images.githubusercontent.com/13607728/37969887-872b8eb2-3204-11e8-8efb-e3d53403f297.png)

**Comment by vmvz** [comment]
ManyToMany 如果太多的时候(特别是OneToOne切换过来的时候), 非常容易卡死. 能不能超过多少的时候只保留前面99-999条?

**Comment by brookshi** [comment]
many to many其他不建议放太多，太多了其实没意义，如果有很多条件，应该分为几个request来放。
以后会做一个正交表结果，这样以最少的组合覆盖最大的可能
