### ISSUE TITLE
本地布署，其它电脑通过ip:port无法登入

### ISSUE THREAD

**Issue by ansonliao** [brookshi/Hitchhiker#14]
Hitchhiker通过docker布署在内部网络某个电脑上(hitchhiker版本为v0.1.3)，端口为1234，其它电脑通过`http://ip:1234`可以打开hitchhiker，但无法登入帐号，提示如下。
本电脑布署，本电脑登入没有问题。

![image](https://user-images.githubusercontent.com/6060224/30791063-9fdc04e4-a1e2-11e7-84dc-fa6941f56fd5.png)

**Comment by brookshi** [comment]
麻烦把浏览器控制台的截图发下

**Comment by ansonliao** [comment]
@brookshi 

![image](https://user-images.githubusercontent.com/6060224/30800813-d729f6c8-a213-11e7-858d-1c6669c2c8fd.png)

**Comment by brookshi** [comment]
是不是docker-compose.yml里用的localhost呢，得用你的局域网ip

**Comment by ansonliao** [comment]
@brookshi 
Oh...是的，改成局域网的ip就可以了。
谢谢解答。

**Comment by lg8294** [comment]
我是部署在公司云服务器上的，服务器做了反向代理，外网访问的是8080端口，hitchhiker配置的是8081端口，也会出现这个问题，有没有什么方法处理呢
