### ISSUE TITLE
定时执行模块，结果均成功，但是显示“失败”

### ISSUE THREAD

**Issue by junjuntj** [brookshi/Hitchhiker#144]
![image](https://user-images.githubusercontent.com/37865579/38242486-82e3f232-3767-11e8-8a4c-2a3a0d72be30.png)
大神，我的定时任务
通过：失败（应该是“成功”）
描述：22：所有通过；25：所有通过；对比：匹配
麻烦帮忙看下啥问题吧

**Comment by junjuntj** [comment]
大神，亲测
request中使用param（one to one）会造成这个问题，切换成many to many就是成功
![image](https://user-images.githubusercontent.com/37865579/38244863-8c824684-376e-11e8-9dca-544619e06153.png)
![image](https://user-images.githubusercontent.com/37865579/38244884-a73a7e6a-376e-11e8-9343-f5243419b867.png)

**Comment by brookshi** [comment]
好的，我看一下哈

**Comment by brookshi** [comment]
@junjuntj hi， 我貌似重现不了，你方便分享一下你出问题的case不

**Comment by brookshi** [comment]
重现不了，如果继续没响应会先关掉，有反应再reopen
