### ISSUE TITLE
当chrome的开发者工具，高度盖过“加载中”的动画时，chrome浏览器页面会卡死，无响应

### ISSUE THREAD

**Issue by 317174106** [brookshi/Hitchhiker#146]
当chrome开发者工具，高度超过“加载中“的动画时，页面会卡死，无响应

![_20180408194825](https://user-images.githubusercontent.com/25921468/38467086-fdcf0eda-3b65-11e8-98f2-bd8f78b919cb.png)

**Comment by vmvz** [comment]
我也出现过
