### ISSUE TITLE
How to accessing variables of environment

### ISSUE THREAD

**Issue by ansonliao** [brookshi/Hitchhiker#15]
Create some variables and save them to environment set, in PostMan, we can use format `{{variable_name}}` to access specified variable in request (url, body in json, etc.), how I can access the variable of environment in Hicchiker?

I found Postman pattern doesn't work in Hichhiker.
please advise.

**Comment by brookshi** [comment]
Also use {{variable_name}} to access, remember select environment before send.
![image](https://user-images.githubusercontent.com/13607728/30802223-5bdd9e34-a218-11e7-9560-decca0b9048f.png)
![image](https://user-images.githubusercontent.com/13607728/30802253-6e25af96-a218-11e7-8c06-7469ec82b70f.png)

**Comment by ansonliao** [comment]
I meant like this:
I have variable in environment, and use this variable in URL, body of JSON, etc., it doesn't work.

![image](https://user-images.githubusercontent.com/6060224/30838721-da499b38-a29f-11e7-808a-d8df99437f69.png)
![image](https://user-images.githubusercontent.com/6060224/30838744-fe3db812-a29f-11e7-8994-bdb0508211a6.png)

**Comment by ansonliao** [comment]
I found it works today.
Thanks.
