### ISSUE TITLE
自动化测试里面，不能对单个接口进行开关不太方便

### ISSUE THREAD

**Issue by gumutianqi** [brookshi/Hitchhiker#151]
@brookshi 

**有个建议：**

自动化测试面只能拖动接口顺序，有的接口比如删除操作，写操作，可能不会每次都去跑，有需要排除某几个接口的情况，跟压力测试一样，可以提供接口的多选框就完美了。

调度器主要用来每日监控生成环境接口是否都Online，但是更新操作的接口是不希望去监控的，主要是Run查询接口。

**Comment by brookshi** [comment]
Duplicate: #140
