### ISSUE TITLE
自定义lib tv4.js

### ISSUE THREAD

**Issue by gleams** [brookshi/Hitchhiker#155]
hitchhiker.require('tv4.js')

Error: Cannot find module '/usr/src/Hitchhiker/build/global_data/952a16f0-3231-11e8-b7d2-4dc292d68e26-HyalZKuqG/lib/tv4.js'

请问这怎么解决

**Comment by ZhangBohan** [comment]
@gleams 可以把问题close了

**Comment by brookshi** [comment]
@gleams 引入Lib时需要遵守Node包的规范，需要有package.json或index.js文件
