### ISSUE TITLE
hitchhiker.setEnvVariable 这个每天写，太长了

### ISSUE THREAD

**Issue by gumutianqi** [brookshi/Hitchhiker#158]
`hitchhiker.setEnvVariable()`

这段每天写几十上百遍，太长了，是不是调整易用短一点好啊。

比如这个《银河系漫游指南》，`hitchhiker`保留不错，情怀。
这个`setEnvVariable`，是不是setEnv就可以了。

另外，题外话：目前的`setEnvVariable`只能在项目内共享，能否有`setGolbalEnv`来跨项目共享，或者是通过其他的方式，saveGolbalFile(K,V)，存到一个可以全局读写的_global.json文件

**Comment by brookshi** [comment]
hitchhiker可以简写为hh，哈哈

**Comment by brookshi** [comment]
另外一个解决方案是在global function里自己定义函数来简写

**Comment by daivvv** [comment]
@brookshi 说到名字  `hitchhiker` 至今我还无法拼全....  postman/paw  这些都是容易一些

**Comment by brookshi** [comment]
@daivvv 这名字确实有点特殊，hh又好像有点怪，回头想个更好的简称
