### ISSUE TITLE
[问题][自定义脚本] 如何导入依赖库

### ISSUE THREAD

**Issue by wilfordw** [brookshi/Hitchhiker#161]
我在尝试上传类似 ioredis 类库 它依赖与 bluebird 和 lodash 等module，会提示 Error: Cannot find module 'xxxx'， 但不知道如何把这些依赖添加进去，我分别上传也解决不了问题

**Comment by brookshi** [comment]
ioredis里的node_modules里包含这些依赖就可以了

**Comment by wilfordw** [comment]
了解， thank you
