### ISSUE TITLE
Schedulers大量的记录导致登录时传输大量的数据

### ISSUE THREAD

**Issue by tonyliu421** [brookshi/Hitchhiker#165]
![image](https://user-images.githubusercontent.com/2101104/39172594-c91c722e-47d4-11e8-94a7-7e2e23e9ebb6.png)

目前只能通过用户定期删除计划任务的记录来避免这个情况

建议登录时不传输计划任务结果集的数据

**Comment by brookshi** [comment]
有没有改过这个配置： "storeContent": "forFail", // schedule record response 是否存储, all表示所有都存下来, forFail表示只存失败的, none表示都不存（这会很大影响数据库大小和性能）    HITCHHIKER_SCHEDULE_STORE_CONTENT

**Comment by tonyliu421** [comment]
直接用docker脚本部署，并没有改过appconfig.json的配置
刚刚检查了docker内appconfig.json的配置确实是 forFail

**Comment by brookshi** [comment]
docker部署可以通过改环境变量来改配置，是不是schedule里有大量失败的呀，如果不关心失败里的body的话可以设为none

**Comment by tonyliu421** [comment]
1 实际我能在schedule看到成功的结果
2 如果配置为none就没有任何response body的记录吗？失败的记录还是需要关心的

**Comment by brookshi** [comment]
这样的话可以设置下存储的大小，多余的会自动清掉。参考配置里 http://doc.hitchhiker-api.com/cn/installation/configuration.html  schedule那个

**Comment by tonyliu421** [comment]
👌，我修改存储大小的配置看看能不能生效

**Comment by tonyliu421** [comment]
存储大小的配置生效的
