### ISSUE TITLE
我尝试使用传递参数为何一点效果都没有

### ISSUE THREAD

**Issue by poipo** [brookshi/Hitchhiker#169]
![image](https://user-images.githubusercontent.com/24470435/39298840-dcc66db0-4979-11e8-8539-0df02b02fd82.png)
![image](https://user-images.githubusercontent.com/13607728/34264854-2569cc98-e6af-11e7-80b7-4bfb50b90665.png)
#57 

像这个的效果，我总是出不来，是不是有什么需要设置

**Comment by brookshi** [comment]
这个只在schedule里有用

**Comment by poipo** [comment]
我知道啊。顺序我也设置了，就是没效果

**Comment by poipo** [comment]
应该是不支持post吧。。。

**Comment by brookshi** [comment]
我的例子不就是post的么

**Comment by poipo** [comment]
不是啊。。。两个请求都是get

**Comment by poipo** [comment]
我在http://www.hitchhiker-api.com/里建了一个Daily，麻烦帮我看看吧。。。。

**Comment by brookshi** [comment]
好了

**Comment by brookshi** [comment]
你是知乎的吗

**Comment by brookshi** [comment]
对了，hitchhikier-api上的例子最好不要改变，可以新加

**Comment by poipo** [comment]
不是。。。只是找了个api试试而已 ，
不好意思，改完才发现，谢谢啦

**Comment by brookshi** [comment]
不客气
