### ISSUE TITLE
请问邮件发不出去怎么解决

### ISSUE THREAD

**Issue by poipo** [brookshi/Hitchhiker#172]
错误：
[2018-05-02 16:11:50.823] [ERROR] default - mail: Mail command failed: 553 Mail from must equal authorized user

谢谢

**Comment by brookshi** [comment]
错误里已经提示了： 邮件里设置的from必须和登录用户一致

**Comment by poipo** [comment]
![image](https://user-images.githubusercontent.com/24470435/39513090-b8e57ffc-4e25-11e8-8abe-17807e2991c5.png)
是指appconfig.json的from和user一致，
还是指from与登陆注册那里邮箱一致

**Comment by brookshi** [comment]
from和user

**Comment by poipo** [comment]
额。。改完重启服务又冒出来一个错误

![image](https://user-images.githubusercontent.com/24470435/39513572-643a2fb4-4e27-11e8-86d0-ebac8c71274c.png)

这是什么问题。。

**Comment by brookshi** [comment]
语言是不是改了，lang只支持 zh或en

**Comment by poipo** [comment]
我是写错过语言，可现在不管是改回zh还是en都会报这个错误

**Comment by brookshi** [comment]
哦，倒没有考虑过这种情况，浏览器cache了错误的语言，应该处理下错误用默认的。
现在可以在流览器的控制台把本地cache清掉.
![image](https://user-images.githubusercontent.com/13607728/39514260-4ceea630-4e29-11e8-86b8-45d6ca4d2bb4.png)
