### ISSUE TITLE
ubuntu 18.04 新安装docker相关  拉取报错 net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by Archer456** [brookshi/Hitchhiker#177]
`cmd@TR:~/hitchhiker$ sudo docker-compose up -d
Creating network "hitchhiker_default" with the default driver
Pulling hitchhiker-mysql (mysql:5.7)...
5.7: Pulling from library/mysql
f2aa67a397c4: Pulling fs layer
1accf44cb7e0: Pulling fs layer
2d830ea9fa68: Pulling fs layer
740584693b89: Waiting
4d620357ec48: Waiting
ac3b7158d73d: Waiting
a48d784ee503: Waiting
bf1194add2f3: Waiting
0e5c74178a02: Waiting
e9201d309436: Waiting
bf1ac4524e8e: Waiting
ERROR: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/0d/0d16d0a97dd13a8ca0c0e205ce1f31f64d9d32048379eb322749442bff35f144/data?Expires=1526068284&Signature=THsVEy9a40kw84ohkweoyG8Ef0NL-HXsaJxnZp3jwd4RfCir02~5alTcfsioqOf8db1~~jaCUgajHMM5~M7dTodTk4wWoo7RHsF0~BZwxYohmC2FZSq2YW1v1Z6yYuTOl~P0xa-LhKs7WbyGXgdBF3TEa1SYTIFglIec93PFeWw_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
`

`cmd@TR:/etc/docker$ docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
`

**Comment by Archer456** [comment]
弄好了 请忽略

**Comment by vmvz** [comment]
@Archer456 你自己可以把这个 issue 关闭一下
