### ISSUE TITLE
docker版不工作

### ISSUE THREAD

**Issue by jshpng** [brookshi/Hitchhiker#18]
![request pending](https://user-images.githubusercontent.com/13727004/30949876-9d547dd0-a44b-11e7-9cbe-b5cb10147173.png)

docker版，跑起来怎么是这样？点“try without login”之后，http://ip:8080/api/user/temp 这个请求一直是pending

**Comment by brookshi** [comment]
是windows上还是linux上的docker呢，这看起来像是数据库没连上， 进到数据库看下

**Comment by jshpng** [comment]
后来我直接跑的代码，可以用。
我是觉得docker版应该拉下来直接就能用，回头我进去仔细看看哈。

**Comment by brookshi** [comment]
应该是拉下来就可以用的，我在服务器上的部署就是这样，没什么问题

**Comment by brookshi** [comment]
有时可能确实第一次启动后不工作，可以进入容器： `sudo docker exec -it hitchhiker bash`，然后在容器里执行`pm2 restart index`就可以了。
原因是使用的数据库ORM在同步schema时可能会同步不上.
