### ISSUE TITLE
语法检查器 [小bug]

### ISSUE THREAD

**Issue by vmvz** [brookshi/Hitchhiker#190]
- await 提示错误
- 没有`;` 有提示
![image](https://user-images.githubusercontent.com/1652700/40592618-2458e1ce-6254-11e8-96d1-5ef353124c0d.png)

**Comment by brookshi** [comment]
这个是用的ace编辑器的js不支持es7的原因，得想办法自定义规则去掉

**Comment by vmvz** [comment]
@brookshi 不影响使用, 那就等 ace自己更新吧, 先做更重要的
