### ISSUE TITLE
Question about export features

### ISSUE THREAD

**Issue by xleliberty** [brookshi/Hitchhiker#191]
Hi, 
thank you very much for this huge project !
A question about export data possibilities.

Have you planned to add possibility to export a project or at least a collection ? 
Would be great if we could export to same formats as provided in imports ( Postman / Swagger )

Thanks

**Comment by brookshi** [comment]
Refer to #107, export feature is in my road map but not high priority. All data store in your mysql database, json is just another storage.
Export to Postman/Swagger need to be considered.

**Comment by xleliberty** [comment]
Thank you for your answer, 
i've just dig into mysql tables and yes, it should be relatively easy to work on an exporter to postman or/and swagger

regards
