### ISSUE TITLE
"try without login" 无法使用

### ISSUE THREAD

**Issue by YiiGuxing** [brookshi/Hitchhiker#2]
Fetch API cannot load http://www.hitchhiker-api.com/api/user/me. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hitchhiker-api.com' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Jwrong** [comment]
你要是自己部署的话，HITCHHIKER_APP_HOST这个配置成自己的ip和端口

**Comment by brookshi** [comment]
这个是我服务器没部署好，nginx设置有点问题，造成 [http://hitchhiker-api.com](http://hitchhiker-api.com)有跨域问题， 加上www就好了，请访问 [http://www.hitchhiker-api.com](http://www.hitchhiker-api.com)
