### ISSUE TITLE
提个小小的意见哈……密码能不能哈希一下不要存明码-。-

### ISSUE THREAD

**Issue by andares** [brookshi/Hitchhiker#200]
看了眼数据库，同事的密码我全知道了，还好我自己用的垃圾码…… 😂

**Comment by brookshi** [comment]
ref: #118，这周末发布

**Comment by andares** [comment]
nice！多问一句，docker下的更新是改改docker image的配置重启一下么？

**Comment by brookshi** [comment]
是的，改下版本号，dock-compose up -d 就可以了

**Comment by andares** [comment]
已更新，手动刷了下密码md5搞定。还解决了丢session的问题，不错的新版本！

顺便问下有没有想法用reasonml重写 😂
