### ISSUE TITLE
对于已保存的接口存在改Headers无效的问题

### ISSUE THREAD

**Issue by liuyuf** [brookshi/Hitchhiker#207]
创建时用的是 application/json。 保存

过段时间改为 application/hal+json 保存。

请求接口还是 application/json

![1529633699692](https://user-images.githubusercontent.com/38779004/41754576-76ae6eca-7605-11e8-8bef-616266cd4b3b.jpg)

**Comment by liuyuf** [comment]
重新创建一个请求 直接用application/hal+json 才行

**Comment by brookshi** [comment]
下面那个headers里显示的是response的content-type，不是发送的。
发送的看console下面的，你的版本是老的吧
![image](https://user-images.githubusercontent.com/13607728/41755183-885cb106-7608-11e8-97b4-b7e3e2876784.png)

**Comment by liuyuf** [comment]
我更新下
