### ISSUE TITLE
请求URL编码问题

### ISSUE THREAD

**Issue by Huarong** [brookshi/Hitchhiker#21]
好像如果URL中，有中文的话，编码会乱

Hitchhiker 中 url: 

![image](https://user-images.githubusercontent.com/1487879/31643655-79b880a4-b2b7-11e7-8a45-6042bdc14dc7.png)

服务器收到的url为：

![image](https://user-images.githubusercontent.com/1487879/31643683-9d37122a-b2b7-11e7-8d55-f99a891e1600.png)

**Comment by brookshi** [comment]
这块倒是没注意到，谢谢提出来，我测试下

**Comment by brookshi** [comment]
测试了下，确实有问题，下个版本会改进，谢谢。

**Comment by brookshi** [comment]
fixed in v0.3
