### ISSUE TITLE
新增内容保存失败问题

### ISSUE THREAD

**Issue by renwenwen** [brookshi/Hitchhiker#211]
现象描述：
打开网页长时间未关闭，期间把Mac电脑合上过，发现之前新增的内容一直无法保存到库里，IN SYNC上一直是红色标记。

**Comment by brookshi** [comment]
刷新一下呢，修改过的内容在浏览器本地也会缓存一份以防丢失，所以刷新一下就可以

**Comment by brookshi** [comment]
没问题就关了，有问题再Reopen

**Comment by renwenwen** [comment]
刷新后修改数据都没了

**Comment by brookshi** [comment]
应该不至于呀，数据保存到本地会有2秒左右的延时，你可以修改后不保存，等2秒刷新试试
