### ISSUE TITLE
Schedule 增加分钟和小时为单位

### ISSUE THREAD

**Issue by Huarong** [brookshi/Hitchhiker#22]
目前只能按照天为单位，希望增加分钟和小时

**Comment by brookshi** [comment]
这个是否过于频繁了呢，之前做schedule时也考虑过，但是有的schedule可能跑完就需要十几分钟，太细粒度了可能就导致schedule一起在跑，而且越积越多

**Comment by Huarong** [comment]
是否过于频繁由使用者来决定。

应该大部分任务很快就能跑完

**Comment by brookshi** [comment]
也有道理，加到计划中

**Comment by brookshi** [comment]
v0.4版本现在支持以小时或分钟为单位了
