### ISSUE TITLE
获取数据失败

### ISSUE THREAD

**Issue by liutf** [brookshi/Hitchhiker#220]
* 问题
![image](https://user-images.githubusercontent.com/14069370/42442123-77d20c9a-839c-11e8-929e-c3da7f371c24.png)

URL：`{{host}}/model_product/user_info/v3?GA2bKApHnmvqAYEFPOIpQNS4GsWeckbtFH9mCbCoFe876Kne&mvnokey=LEWr7s0&timestamp=2018-06-13%2016:12:55&serial_number=GA2bKApHnmvqAYEFPOIpQNS4GsWeckbtFH9mCbCoFe876Kne&service_type=basic_service&service_name=user_info&api_name=cu.vop.model_product.user_info&phone_number=17193086312`

host为http://localhost:8081，发送时获取失败。

host改为本机对应的局域网IP：192.168.20.30后，可以访问。

* 期望
能支持localhost

**Comment by brookshi** [comment]
哦，用docker的话，localhost会指向容器的虚拟ip，可以修改localhost mapping.
参考这个文档的最下面：
http://doc.hitchhiker-api.com/cn/Simple_Tutorial/Create_Project.html

**Comment by liutf** [comment]
这个办法确实是可行。
![image](https://user-images.githubusercontent.com/14069370/42483373-a8f31570-841f-11e8-93da-2f188f30305f.png)
