### ISSUE TITLE
关于run now对外接口的疑问

### ISSUE THREAD

**Issue by liuyuf** [brookshi/Hitchhiker#221]
这个URL是需要登录权限才能成功执行吗，我在没有登录时请求URL返回了失败

![image](https://user-images.githubusercontent.com/38779004/42443309-afa99ba8-839f-11e8-8211-5984fb49530f.png)

**Comment by brookshi** [comment]
嗯， 所以文档上写着`记得在url或header里把http authorization传上`

**Comment by brookshi** [comment]
具体怎么传可以网上搜下

**Comment by liuyuf** [comment]
好的 谢谢
