### ISSUE TITLE
LTS是什么

### ISSUE THREAD

**Issue by SpringStudent** [brookshi/Hitchhiker#223]
是light-task-scheduler吗

**Comment by brookshi** [comment]
不小心关了，LTS是在哪看到的，一般来说LTS的意思是指Long-Term Support

**Comment by SpringStudent** [comment]
ok

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/42491358-13d22968-8447-11e8-8361-ae9dd4460410.png)
卡在这里了
