### ISSUE TITLE
很赞，感谢作者

### ISSUE THREAD

**Issue by SpringStudent** [brookshi/Hitchhiker#224]
![image](https://user-images.githubusercontent.com/14833956/42498725-8bd0fbb6-845f-11e8-9281-1a8380bf0fb8.png)
这个怎么做有没有Demo

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/42501787-1002383a-8467-11e8-9cc5-f657630b27c0.png)
压力测试task停止不掉即使被删除

**Comment by brookshi** [comment]
issue最好是分开提，这样方便解决和检索

**Comment by brookshi** [comment]
第一个： 没写具体的demo，只是利用一个变量即可解决，可以参考sample里变量相关的例子
第二个：菜单里有一个stop的功能，这块未来会改进下

**Comment by SpringStudent** [comment]
很不错的工具tks

**Comment by brookshi** [comment]
谢谢支持 😄
