### ISSUE TITLE
Response返回的json串可以与mysql中的数据对比吗

### ISSUE THREAD

**Issue by duqinghong** [brookshi/Hitchhiker#225]

**Comment by duqinghong** [comment]
我想把结果中的json串与我项目中的mysql数据表的数据进行比较，能实现吗

**Comment by duqinghong** [comment]
可以具体点，告诉我在哪引吗，怎么使用

**Comment by brookshi** [comment]
参考文档： http://doc.hitchhiker-api.com/cn/Script/custom-javascript-lib.html
如果不了解node的话可能会比较麻烦

**Comment by duqinghong** [comment]
好的，多谢，敢快恶补去

**Comment by brookshi** [comment]
ok, 过程中有什么问题可以收集起来发给我，我有时间就会解答下
