### ISSUE TITLE
URL encode时对参数中+号的encode结果不正确，预期是%2B，实际将+号作为URI中的空格编码为%20

### ISSUE THREAD

**Issue by walbx** [brookshi/Hitchhiker#226]
- **现象:** 平台在`Generate request options`阶段对`url`做默认`encode`时，query string参数值中的`+`号被识别为URI的空格，得到的编码是空格的编码`%20`，而不是期望的`%2B`。
- **问题:** 如下常见场景中可能引发问题：当接口签名算法涉及Base64编码，或者在搜索接口中搜索字符串中存在`+`号时，将会导致签名错误或者查询结果与预期不一致的情况。
- **case:** 一个POST接口，content-type选择x-www-form-urlencoded，接口中
`sign=z9+Lc7Ed9JZQSRBpNYlEfIm0BrM=`这组queryString参数，hitchhiker日志里面看转码出来是`sign=z9%20Lc7Ed9JZQSRBpNYlEfIm0BrM%3D`，预期是`sign=z9%2BLc7Ed9JZQSRBpNYlEfIm0BrM%3D`
- **我的临时解决办法：** 将包含`+`号的参数组放在body中以form形式提交。但如果其他用户的被测服务对于入参有严格要求的情况，这个临时办法无法解决
- **其他：** 考虑使用`encodeURIComponent()`对query string部分的参数进行编码;

**Comment by brookshi** [comment]
嗯，重现了，已经做了encodeURIComponent()，但是之前的URL.parse有问题
