### ISSUE TITLE
接口怎么排序？

### ISSUE THREAD

**Issue by liutf** [brookshi/Hitchhiker#228]
![image](https://user-images.githubusercontent.com/14069370/42792002-e11fcf34-89a5-11e8-9911-d0372e282895.png)

请问下接口怎么指定显示顺序？因为有些业务接口是有顺序的。

**Comment by brookshi** [comment]
是按名字排序的，如果要在collection里排序可以在名称前面加上序号
Scheduler里面是支持拖动排序的

**Comment by brookshi** [comment]
Collection里的拖动排序有issue已经提出来，后面会实现

**Comment by liutf** [comment]
OK，那我先关闭。期待更新。
