### ISSUE TITLE
邮件通知失败

### ISSUE THREAD

**Issue by wei1000** [brookshi/Hitchhiker#235]
按照文档配置了邮件，忘记密码功能可以收到Hitchhiker发送到修改密码通知邮件。但是自动化测试项目中的通知功能，无法成功发送邮件，后台日志又显示send mails.

**Comment by brookshi** [comment]
我这边是能收到的，如果schedule跑成功的话默认是不发邮件的，如果成功也需要发送需要设置下环境变量

**Comment by wei1000** [comment]
确实是成功不会发送邮件，失败后收到邮件了。麻烦，请问成功需要发送邮件如何修改环境变量呢

**Comment by brookshi** [comment]
http://doc.hitchhiker-api.com/cn/installation/configuration.html 
`"mailOnlyForFail": true // 只在失败时发邮件   HITCHHIKER_SCHEDULE_MAILFORFAIL`
如果等周末的版本就可以在schedule的edit里直接设置

**Comment by wei1000** [comment]
非常感谢
