### ISSUE TITLE
schedules 没有运行

### ISSUE THREAD

**Issue by Huarong** [brookshi/Hitchhiker#24]
按照要求设置了shedules，但是没有任何地方显示按照预订时间执行了

**Comment by brookshi** [comment]
刷新下看看，schedule有两种方式可以跑，一种是菜单里的Run now， 另一种是按时间来，Run now可以看到实时跑，按时间的是在后台跑，前台看不到

**Comment by Huarong** [comment]
刷新过了
run now 可以正常跑，但是出错无法收到邮件通知
我设置了一个按照时间跑，虽然是在后台跑，但是应该也在网页端显示最后的运行结果呀，现在什么都没有显示

**Comment by brookshi** [comment]
嗯，后台跑网页刷新后会有显示结果，schedule目前是半小时检测一次，所以可能是还没去检测，这个时间间隔可以在appconfig.json下面调

**Comment by Huarong** [comment]
已经过了两个半小时了，还是没有显示
而且，我用的docker版本，应该调不了吧？

**Comment by brookshi** [comment]
哦，还有个原因，如果在那段时间内Run now过，schedule会认为不需要再自动run了。
docker也可以，在run docker时设置下环境变量HITCHHIKER_SCHEDULE_DURATION就可以

**Comment by Huarong** [comment]
> 如果在那段时间内Run now过，schedule会认为不需要再自动run了

这个假设值的商榷

**Comment by bfyxzls** [comment]
您好，这个run Now的动作可以由外部触发吗，比如jenkins去调用它

**Comment by brookshi** [comment]
不能，因为现在run now是基于websocket的，如果只是想要一个run now的接口的话倒不是什么难事，下个版本可以加进来

**Comment by bfyxzls** [comment]
您说，我有这样一种场合，对于schedules来说，有很多接口，而这些接口可能依赖于一个登陆接口，我看咱们是并行执行，没有顺序的，请问如何让一个接口优先执行呢？

**Comment by brookshi** [comment]
是可以顺序执行的，schedule的edit dialog里有个sort request

**Comment by bfyxzls** [comment]
好的，找到了，谢谢！
还有一个就是咱们有后台用户的地方吗，我有个用户在操作测试时，出现了unknow的错误，随后再登陆就500了，可能是有垃圾数据了

**Comment by bfyxzls** [comment]
还有我看咱们的系统地址和端口是在环境变量里的，而在build/index.js里的端口是从appconfig.json里获的，这块有点不统一，因为在修改环境变量端口后，咱们的系统是不能正常使用的，只能把index.js里的端口也改成一样的才行，这块建议在index.js里做的处理，我现在是把它外挂出来了。

**Comment by brookshi** [comment]
暂时还没有管理平台，这个算是后面的一个大的计划里的模块，暂时还是以功能优先。
端口这个确实是个问题，之前没注意到，谢谢指正。

**Comment by bfyxzls** [comment]
老大，还有就是咱们调度时，排序还是有BUG，它没按着我的顺序进行测试：）

**Comment by brookshi** [comment]
不会吧，我这边都是可以的

**Comment by bfyxzls** [comment]
我这边进行的是拖动修改顺序，但结果与我妥的不一样，确实很奇怪

**Comment by brookshi** [comment]
跑出来的结果是没作排序的，只是跑的时候按顺序跑

**Comment by brookshi** [comment]
你是有设compare吗，compare的话是跑完一个环境的再跑令一个环境的

**Comment by bfyxzls** [comment]
没有compare的，只是一个环境的，这个FAQ没有图片，要是可以上传图片就可以让您看到效果了

**Comment by brookshi** [comment]
直接粘贴图片就可以了

**Comment by bfyxzls** [comment]
![default](https://user-images.githubusercontent.com/1975414/32487384-87d421e6-c3e4-11e7-9bd1-c97066f5ebd4.png)
![default](https://user-images.githubusercontent.com/1975414/32487413-961ba008-c3e4-11e7-9d00-c4aff83a0e2c.png)

**Comment by bfyxzls** [comment]
真是万能的编辑器！

**Comment by brookshi** [comment]
看起来是有问题，我回去研究下，谢谢

**Comment by bfyxzls** [comment]
谢谢您！还有希望您在email里，可以有个报表查看的链接，比如一些报表图，因为列表不是很直观！谢谢！

**Comment by brookshi** [comment]
嗯，这个是好个提议，会加到计划中

**Comment by bfyxzls** [comment]
您好，昨天咱们说的那个顺序的问题，您那边啥时能调整好：）

**Comment by brookshi** [comment]
下个版本，大概下周一或者周二

**Comment by brookshi** [comment]
不过倒是可以先把代码写过去，不过不会做docker镜像，你如果是用代码部署的话明天可以更新下release分支的代码，我今晚fix掉

**Comment by bfyxzls** [comment]
噢，好的，不过我确实是使用docker来做的这事:<

**Comment by brookshi** [comment]
那就只能等下周了，时间有限，发布要花不少时间，只能集中做了

**Comment by bfyxzls** [comment]
使用websocket到是避免了轮训更新状态列表，这个设计挺好！

**Comment by bfyxzls** [comment]
好的，那下周等您通知！

**Comment by bfyxzls** [comment]
您好，咱们的新版发布了吗，就是修改排序问题的，就是docker上的版本

**Comment by bfyxzls** [comment]
好了，我看到新的v0.4了，辛苦！

**Comment by brookshi** [comment]
稍等，测试还没完成，打tag是为了测试一个docker上的东西，明天应该会发布

**Comment by bfyxzls** [comment]
噢，不过我已经测试了，排序好了：）

**Comment by brookshi** [comment]
代码已经进去了

**Comment by brookshi** [comment]
@bfyxzls 
排序好了应该知道了，另外 run now也开放了接口给外部调用，可以参考 [文档](https://github.com/brookshi/Hitchhiker/blob/master/doc/howtouse-cn.md#schedule)
另外的一个用图表展示schedule结果的功能希望可以单独提个issue，这个就先关了
