### ISSUE TITLE
修改headers或body中的描述后，点击保存没有反应

### ISSUE THREAD

**Issue by wangyunshuai** [brookshi/Hitchhiker#248]
**1. What went wrong `(哪里出错)`?**
修改headers或body中的描述后，点击保存没有反应

**2. Steps to reproduce the problem `(重现步骤)`:**
点击“保存”按钮

**3. What is the expected behavior `(期望表现)`?**
执行保存的操作

**4. Did this work before `(之前是否正常)`?** 
0.13版本没有用过

**5. Environment `(环境)`:**
 - V0.14
 - docker安装

**Comment by brookshi** [comment]
我在本地测试没有这问题，body也没有描述

**Comment by brookshi** [comment]
ok，重现了，是由于仅修改description时没激活请求处于已经修改状态。
