### ISSUE TITLE
help 403

### ISSUE THREAD

**Issue by 184609680** [brookshi/Hitchhiker#25]
http://192.168.0.250:8080/api/user/me
403
![qq 20171019152158](https://user-images.githubusercontent.com/13617217/31758759-56b72278-b4e1-11e7-8a8d-6027fb260b5b.png)

**Comment by brookshi** [comment]
这个url 403 正常的，不过你是注册估计请求在pending状态，可以看network，是用docker吗

**Comment by 184609680** [comment]
没有用docker，一直在pending
![qq 20171019162047](https://user-images.githubusercontent.com/13617217/31761117-7c11658a-b4e9-11e7-846c-ae1ab16ffd0a.png)

**Comment by brookshi** [comment]
看起来是数据库没连上，看下logs/下面的Log

**Comment by 184609680** [comment]
可以了，看了下是要升级下mysql版本

**Comment by brookshi** [comment]
好
