### ISSUE TITLE
全局脚本引用不到

### ISSUE THREAD

**Issue by liutf** [brookshi/Hitchhiker#250]
* 问题
定义了全局脚本，引用不到

- 定义全局脚本

![image](https://user-images.githubusercontent.com/14069370/43634025-a8dd4cf0-973d-11e8-84e4-7308cf7a4924.png)

- 引用
![image](https://user-images.githubusercontent.com/14069370/43633995-8b6bfd06-973d-11e8-87ab-0968c6d0f455.png)

- 结果
![image](https://user-images.githubusercontent.com/14069370/43634063-bb5989e8-973d-11e8-91a6-68151f4f977d.png)

* 期望
 能引用到。  请问是我的方式不对吗？

**Comment by brookshi** [comment]
新请求不属于任何project，所以这个project下的全局脚本用不上，先保存到一个project下

**Comment by liutf** [comment]
果然是这个原因，谢谢！
