### ISSUE TITLE
tap

### ISSUE THREAD

**Issue by jennyjane** [brookshi/Hitchhiker#258]
**1. What went wrong `(哪里出错)`?**
Please describe what went wrong (请描述bug的具体表现)

**2. Steps to reproduce the problem `(重现步骤)`:**
Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner (简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在)

**3. What is the expected behavior `(期望表现)`?**
Please describe the expected behavior (请描述期望表现)

**4. Did this work before `(之前是否正常)`?** 
[Yes, No, N/A] [是，否，之前没用过]

**5. Environment `(环境)`:**
 - Hitchhiker Version (Hitchhiker版本): [e.g. V0.14]
 - Use Docker or Installation Package (使用Docker还是安装包): [e.g. Docker/Installation Package]
 - Node Version (If you use the installation package) (如果使用安装包的Node版本): [e.g. 8.11.3]
 - Server OS (部署的系统): [e.g. Ubuntu, Windows, MacOS]
 - Browser (浏览器): [e.g. Chrome, Firefox, Safari]

**6. Additional Information (e.g. Screenshots, Links) `(补充信息，截图，链接等)`**
Add any other context about the problem here (补充具体的上下文信息)

**Comment by jennyjane** [comment]
能否加一个关闭全部tab，关闭其他tab的功能
![image](https://user-images.githubusercontent.com/19267219/44459808-7ae76100-a63d-11e8-9965-6c5dc5dd49b5.png)

**Comment by brookshi** [comment]
已经有了，在tab右边+按钮的旁边
