### ISSUE TITLE
是否支持生成请求的签名

### ISSUE THREAD

**Issue by kkfnui** [brookshi/Hitchhiker#26]
为了接口安全，有些接口协议会定义签名。
比如使用接口请求参数的 md5 作为签名，然后将签名放在 HTTP Header 中。

请问现在是否可以支持呢？

**Comment by kkfnui** [comment]
https://testerhome.com/topics/5733

应该也是支持 prepostscript 的吧

**Comment by brookshi** [comment]
pre request script暂时还没支持，不过在计划中，还请稍等下（大概三周左右）

**Comment by brookshi** [comment]
@kkfnui 
v0.4版本现在支持这个功能了，而且比postman强大很多，可以上传任何想用的脚本来做事，默认已经带了一些库，其中就有生成md5的，敬请使用
