### ISSUE TITLE
can not start in windows

### ISSUE THREAD

**Issue by 184609680** [brookshi/Hitchhiker#260]
use 
`npm i`
`gulp build`
`pm2 start pm2.json`

show
`script not found e:/project/github/Hitchhiker-master/build/index.js`

sure not have index.js

how can i do next?

**Comment by brookshi** [comment]
If you want to run Hitchhiker by using source code, reference to https://github.com/brookshi/Hitchhiker/blob/master/deploy/docker/Dockerfile
