### ISSUE TITLE
接口文档的一些改进建议

### ISSUE THREAD

**Issue by wch352136** [brookshi/Hitchhiker#262]
现有的接口文档功能还有一些缺失，最大的不便就是没有返回结果展示。所以有如下建议：
1.添加新接口的时候，在下面增加成功示例和失败示例的输入框
![image](https://user-images.githubusercontent.com/17609338/44983152-cc331100-afaa-11e8-98b5-67d9ad2e65a0.png)

2.查看文档的时候，可以在下方展示预期结果
![image](https://user-images.githubusercontent.com/17609338/44983202-f97fbf00-afaa-11e8-8cf7-d148b77c0bc0.png)

**Comment by brookshi** [comment]
嗯，文档这块是需要改进
duplicate: #257
