### ISSUE TITLE
绿色颜色问题

### ISSUE THREAD

**Issue by rxda** [brookshi/Hitchhiker#272]
基于UI的断言和GET请求的绿色太亮了，有点晃眼，请问可以自己更换颜色么？谢谢
![image](https://user-images.githubusercontent.com/19545808/48240259-3209a200-e40d-11e8-9cfc-d7807e19884b.png)

**Comment by vmvz** [comment]
get 绿色 挺好, 右边的可以考虑换

**Comment by brookshi** [comment]
自己不太好换，我下个版本换个深点的颜色
