### ISSUE TITLE
中文不友好

### ISSUE THREAD

**Issue by VectorHo** [brookshi/Hitchhiker#3]
### 2、如果body有中文，是否支持

**Comment by brookshi** [comment]
是部署在本地的还是访问 http://www.hitchhiker-api.com/ 呢，不支持中文是数据库没设置成utf8引起的

**Comment by VectorHo** [comment]
http://fred.itxfd.com/2016/05/24/mysql-%E4%BF%AE%E6%94%B9%E5%AD%97%E7%AC%A6%E9%9B%86/

**Comment by VectorHo** [comment]
好的，我也找到了原因，拉代码就可以？

**Comment by brookshi** [comment]
嗯， 是的，改了hitchhiker-mysql.cnf和docker-compose.yml，重新取下就可以了

**Comment by brookshi** [comment]
是用代码部署的还是docker呢，其实不是代码的问题呀，用代码部署的需要重新用utf8 来 create database
