### ISSUE TITLE
API 希望可以支持从Swagger导入

### ISSUE THREAD

**Issue by gumutianqi** [brookshi/Hitchhiker#30]
@brookshi 

swagger已经成为API文档的规范了；

Mock 可以参考：https://github.com/easy-mock/easy-mock

**Comment by brookshi** [comment]
这倒是，不过目前只能曲线救国，先导入postman，再导入hitchhiker了，当然这个尽早会支持swagger的，不过优先实现更有用的功能

**Comment by brookshi** [comment]
fixed in v0.7
