### ISSUE TITLE
最新代码编译出错

### ISSUE THREAD

**Issue by youwi** [brookshi/Hitchhiker#32]
@brookshi 试试 在一台纯新机器上编译看看.
我这里报  DotHeader[] 和 DotHeader[]|null  (可能为空)类型不匹配.
ts --version 2.5.3

**Comment by brookshi** [comment]
ts 2.4以上引入了一个破坏性改动，我这边暂时还没有适配，所以需要用2.4.3来编译

**Comment by youwi** [comment]
谢谢.

**Comment by brookshi** [comment]
不好意思，今天确实碰到了这个问题，谢谢你的指正，我还以为是之前升级typescript时碰到了，最新release的0.4版本fix了。
