### ISSUE TITLE
系统提醒通知支持自定义get/post请求或者指定SMTP服务

### ISSUE THREAD

**Issue by mikuazusa** [brookshi/Hitchhiker#34]
一个建议：
系统提醒通知支持自定义get/post请求或者指定SMTP服务，这样可以自行对接各种各样的聊天机器人实现更方便的自动化提醒，拓展性更强。

**Comment by brookshi** [comment]
这还真没想到，之前是打算把SMTP服务放出来，自定义get/post请求这个没想到，确实是好，谢谢建议。

**Comment by gumutianqi** [comment]
自定义就是支持 Hook API 事件通知，这个好，Git 的自动化部署就是通过 Hook 来出发的

**Comment by brookshi** [comment]
@mikuazusa @gumutianqi 
0.4版本发布了，email支持自定义的post 请求

**Comment by brookshi** [comment]
0.7版本支持自定义SMTP了
