### ISSUE TITLE
linux部署

### ISSUE THREAD

**Issue by aicekiller** [brookshi/Hitchhiker#35]
请问下Linux上部署成功是什么样子的呢？
![image](https://user-images.githubusercontent.com/7371862/32215163-2f43752c-bdef-11e7-8712-fbdf38f4c875.png)
我卡在这一步就执行不下去了。

![image](https://user-images.githubusercontent.com/7371862/32215204-51f22ac8-bdef-11e7-82a7-e467887b6a64.png)

**Comment by brookshi** [comment]
compiler client这步会花比较久的时间，根据机器配置，如果配置很低可能会完不成，比如内存1g，webpack打包需要大些的内存，部署完后会提示，为什么不用docker呢，docker直接用就没有这些问题了，也很快

**Comment by aicekiller** [comment]
哦，多谢，我试试。
