### ISSUE TITLE
安装时，能提供配置数据库名，账号，密码的方式吗？乱。

### ISSUE THREAD

**Issue by wuchuguang** [brookshi/Hitchhiker#36]
还有试用了demo. save as能指定保存到的目录。但不能指定新名字。

**Comment by brookshi** [comment]
```
        host: HITCHHIKER_DB_HOST
        port: HITCHHIKER_DB_PORT
        username:HITCHHIKER_DB_USERNAME
        database:MYSQL_DATABASE
        password: MYSQL_ROOT_PASSWORD
```
用上面的环境变量来配置，如果是docker就写在yml文件里，如果是用脚本安装的就写在pm2.json里。
save as 可以在保存后再改

**Comment by wuchuguang** [comment]
这个好用。
保存时，选择分类，这个分类不区分项目的吗？另一个目录下的分类也在本项目可以选到。

**Comment by brookshi** [comment]
这个不区分哦，可能就是想存到另一个项目下去

**Comment by wuchuguang** [comment]
这样子，一个公司部暑一个api服务器，多个项目，就不是很好管理了。再说每个项目的成员也不一样。

**Comment by brookshi** [comment]
哦，那不会，只会显示跟自己相关的项目，你不在的项目里面你是看不到的
