### ISSUE TITLE
这个api工具看起来很nice啊，但是我使用docker-compos 启动8080，并访问注册时 遇到如图错误。匿名使用也不行，mac最新版docker

### ISSUE THREAD

**Issue by acf77** [brookshi/Hitchhiker#37]
![image](https://user-images.githubusercontent.com/18472835/32308587-a6c5d78c-bf54-11e7-8c12-efb4ed6c7c5c.png)

**Comment by acf77** [comment]
docker-compose.yml 内容如下：
![image](https://user-images.githubusercontent.com/18472835/32308717-5256b616-bf55-11e7-88d0-3da0de1410be.png)
似乎是api请求错误。希望抽空看看

**Comment by brookshi** [comment]
跨域问题，试下用localhost:8080访问

**Comment by athrunsun** [comment]
@brookshi `127.0.0.1` 和 `localhost` 不是一回事？
