### ISSUE TITLE
There is no valid Hitchhiker-Node, please run a Hitchhiker-Node first

### ISSUE THREAD

**Issue by 184609680** [brookshi/Hitchhiker#38]
Stress test功能报这个是需要什么？

**Comment by brookshi** [comment]
需要运行一个[Hitchhiker-Node](https://github.com/brookshi/Hitchhiker-Node)， 在[release](https://github.com/brookshi/Hitchhiker-Node/releases)页面可以下载对应平台的，下载后把config下的ip改成server的就可以了

**Comment by 184609680** [comment]
好的，我看一下
