### ISSUE TITLE
建议作者检查可编译性

### ISSUE THREAD

**Issue by youwi** [brookshi/Hitchhiker#39]
编译都过不了.
问题1: Cannot find namespace '_'.  (loadsh全局导入了,但是没有配置)
问题2: XXXXX is declared but never used. (肯定是你的本地配置和git上的配置不一样)

很多前端开发都无视npm生态的不稳定性. 不考虑提交的代码重新npm install 还能不能运行(全新安装)
作者也属于其中一员

**Comment by brookshi** [comment]
用的release分支吗， master分支可能会有问题，release分支不应该有

**Comment by youwi** [comment]
3ks
