### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by mikuazusa** [brookshi/Hitchhiker#40]
更新0.4版本以后，更改schedule的Period为分钟，然后再修改为天，就出现了以下报错：

Warning Message
save schedule failed, Error: Payload Too Large, Retry 5th time after 32000s

**Comment by brookshi** [comment]
我这里没有重现，不过猜测到原因应该是post的数据太大了，把记录也post上去了,因为记录现在最高增加到50条，等会测试下，现在的workround可能需要新建一个schedule了

**Comment by brookshi** [comment]
查了下，应该是引用 的一个body-parse的中间件有对post数据做了1M大小的限制，这两天发个小版本v0.4.1来修复

**Comment by brookshi** [comment]
fixed in v0.4.1
