### ISSUE TITLE
如何在Pre Request Script 里面修改request对象?

### ISSUE THREAD

**Issue by zzjin** [brookshi/Hitchhiker#41]
RT 本来是a=b,在脚本里面怎么自动加上hash签名?(只是举例)
按照postman的语法 直接修改request变量提示不存在

**Comment by brookshi** [comment]
这个可以使用变量，比如a={{b}}, 在pre request script里用hitchhiker.setEnvVariable('b', hash)就可以了

**Comment by zzjin** [comment]
@brookshi 但是我的hash计算需要知道接口请求时候的`b`这个值...

**Comment by brookshi** [comment]
这个b也是变量吗，可否给个例子，谢谢

**Comment by zzjin** [comment]
就是我们会发起一个post请求,里面是一组参数 比如`id=1&path=xyz`,然后希望请求的之前获取到这个请求data,然后对他做一个自定义的hash(假设是crc32)
实际上服务器接收到的data是:
`id=1&path=xyz&hash=57097b12` 
实际的hash算法是另外的,这里只是个自动计算+append的例子

**Comment by zzjin** [comment]
这个body肯定每次请求和每个接口都是动态的呀...就是请求的query部分

**Comment by brookshi** [comment]
那动态的值是配置在变量里的吗

**Comment by zzjin** [comment]
不是,就是手写的,比如同样请求/detail接口,第一次的id=1,第二次就可能是id=29867了.
没法配置成变量去替换吧?

**Comment by brookshi** [comment]
估计说起来不容易理解，我在 http://www.hitchhiker-api.com/  里建了个账号： #42@test.com 密码：424242 ， 可以在里面建个request试下

**Comment by brookshi** [comment]
那对于单个测试接口来说这些是固定的，那就可以直接写到脚本里面，或者说是想写个通用的脚本函数，其他接口直接调用？

**Comment by zzjin** [comment]
进不去这个号 就是说一个project下面的所有的请求都会自动把接口请求的参数hash加上去 project下面可能有很多接口,一个接口下面也会有不同的参数配置

**Comment by brookshi** [comment]
哦，理解，算是一个全局的应用到所有请求的脚本是吧，是个好需求，这个postman能做到吗，以前没注意过。

**Comment by zzjin** [comment]
postman可以实现对request的整体的替换,但是只能一个请求一个的配置(虽然脚本是一摸一样的复制粘贴)

**Comment by brookshi** [comment]
是的，我知道的postman也只能做到这样，Hitchhiker现在脚本里面不能访问到request，不过加上不是难事，下个版本加起来，另外可以考虑做一个应用到整个collection的全局脚本

**Comment by zzjin** [comment]
另外单独提一个点..能不能用户A创建了一个项目之后能主动把用户B打到自己的这个项目来,现在只能发邮件对mail系统和流程都有要求(没外网)

**Comment by brookshi** [comment]
是的，也考虑过，觉得是应该加个开关，可以不发邮件直接加到项目来

**Comment by brookshi** [comment]
可以再提个issue，免得我忘了

**Comment by brookshi** [comment]
功能完成，参考：[脚本API](http://doc.hitchhiker-api.com/cn/Script/API.html)里的request和setRequest
