### ISSUE TITLE
希望文档可以增加一些Pre Request Script 和 Test的进阶使用

### ISSUE THREAD

**Issue by gumutianqi** [brookshi/Hitchhiker#43]
如题

**Comment by brookshi** [comment]
嗯，也是这么想的，要整理下文档

**Comment by gumutianqi** [comment]
@brookshi 文档建议使用 gitbook 来编写，有调理，有目录，从入门到精通，以后出书

**Comment by brookshi** [comment]
哈哈，倒是想写得更好些，不过时间有限，可能暂时只能是整理归类下了

**Comment by brookshi** [comment]
在gitbook整理了文档，地址： [https://www.gitbook.com/book/brookshi/hitchhiker/details](https://www.gitbook.com/book/brookshi/hitchhiker/details)，不过gitbook老是被墙，把它导出到网站上了，可以参考：[http://doc.hitchhiker-api.com](http://doc.hitchhiker-api.com/cn/introduction.html)
