### ISSUE TITLE
Consider implementing no-follow-redirect

### ISSUE THREAD

**Issue by athrunsun** [brookshi/Hitchhiker#44]
Hi,

This might be a dumb question but is there any way or any settings I can use to turn off automatically following redirect?

**Comment by brookshi** [comment]
Hi, 

Sorry, Hitchhiker doesn't support no-follow-redirect yet. it's easy to support it, i'll implement it in v0.5.
One thing i wonder is which level this setting should be:  request, collection or project.
What do you think?

Thanks,

**Comment by athrunsun** [comment]
Hey @brookshi ,

Thanks for your feedback.

For simplicity I think we can put it at global level, in the global settings.

**Comment by brookshi** [comment]
Does global mean project level? Sometimes there are different Collections in a project with different business logic, project level setting may not suitable for this case. What about Collection level, it's between Project and Request， could meet most of requirements.

**Comment by brookshi** [comment]
Get it. But Hitchhiker is created for team which is different from Postman,  a global request setting doesn't seem to make sense for multiple projects.

**Comment by athrunsun** [comment]
@brookshi OK, if that is the case, go ahead with collection level. Thanks!

**Comment by brookshi** [comment]
Thank you for understanding. 😄

**Comment by athrunsun** [comment]
@brookshi No, don't thank me. I should thank you for accepting this feature request. 😃

**Comment by brookshi** [comment]
fixed,  a new option in Collection's menu named `Request Follow Redirect`, default is false.
