### ISSUE TITLE
请问在压测过程中如何随机请求参数

### ISSUE THREAD

**Issue by wallezhang** [brookshi/Hitchhiker#45]
压测场景如下，在请求参数中需要有一个随机数之类的ID，请问基于现有的版本，可以实现吗？

**Comment by brookshi** [comment]
现在Web是可以在Pre Request Script里做到的，不过压测那边还没跟上，需要再等会。

**Comment by wallezhang** [comment]
好的，多谢！期待压测支持 😄

**Comment by brookshi** [comment]
@wallezhang 压力测试现在支持所有脚本特性了，欢迎使用：）
