### ISSUE TITLE
接受图片可以优化下吗

### ISSUE THREAD

**Issue by 184609680** [brookshi/Hitchhiker#47]
![default](https://user-images.githubusercontent.com/13617217/32869804-defd6b14-cab3-11e7-8a67-6bcf3f0e66d8.png)

**Comment by brookshi** [comment]
哈哈，确实有点难看，回头修复下，response header有image的头吧

**Comment by 184609680** [comment]
有的

**Comment by brookshi** [comment]
@184609680 图片已经可以显示了
