### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by 184609680** [brookshi/Hitchhiker#48]
按照说明的填写，但是没有反应
![2](https://user-images.githubusercontent.com/13617217/32871128-45c583f8-caba-11e7-8525-d3942b75fab9.png)
![default](https://user-images.githubusercontent.com/13617217/32871129-46163a50-caba-11e7-9bcf-87b263f55903.png)
![1](https://user-images.githubusercontent.com/13617217/32871131-478a379c-caba-11e7-9135-7124ee07d774.png)
![3](https://user-images.githubusercontent.com/13617217/32871132-47ffa144-caba-11e7-89df-ba0c80cc986d.png)

**Comment by brookshi** [comment]
变量刚试了是没有问题的，感觉是否是你的api能不连通呢，对method是post也有点好奇

**Comment by brookshi** [comment]
close
