### ISSUE TITLE
启动后登录注册都是一直转圈是怎么回事？

### ISSUE THREAD

**Issue by teddymail** [brookshi/Hitchhiker#5]
之前注册登录显示类型错误的那种提示，现在显示这个错误{success: false, message: "session is invalid"}  403其他的不知道，我使用的是docker部署啊

**Comment by brookshi** [comment]
是不是用机器名访问的呢，用ip试试看

**Comment by teddymail** [comment]
IP访问的

**Comment by brookshi** [comment]
可否打开浏览器控制台，截个图我看下

**Comment by teddymail** [comment]
我删除后从新安装一遍后发现数据库起不来了，应该是数据库这块配置有问题吧

ERROR: for hitchhiker-mysql  Cannot start service hitchhiker-mysql: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/root/hitchhiker/hitchhiker-mysql.cnf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/579f1179f3d8a6fe870af03081287389dd474d8daa69aa1c799549f97d909796/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/579f1179f3d8a6fe870af03081287389dd474d8daa69aa1c799549f97d909796/rootfs/etc/mysql/conf.d/hitchhiker.cnf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"

ERROR: for hitchhiker-mysql  Cannot start service hitchhiker-mysql: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/root/hitchhiker/hitchhiker-mysql.cnf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/579f1179f3d8a6fe870af03081287389dd474d8daa69aa1c799549f97d909796/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/579f1179f3d8a6fe870af03081287389dd474d8daa69aa1c799549f97d909796/rootfs/etc/mysql/conf.d/hitchhiker.cnf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.

**Comment by brookshi** [comment]
看起来是hitchhiker-mysql.cnf这个文件不能去到/rootfs/etc/mysql/conf.d这个文件夹，说\\\不是一个目录， \\\这个是怎么来的呢

**Comment by teddymail** [comment]
按照docker部署的方式有以下配置文件

[root@localhost hitchhiker]# cat docker-compose.yml 
version: '2'
services:
  hitchhiker:
    image: brookshi/hitchhiker:v0.1.1
    container_name: hitchhiker
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
      - HITCHHIKER_APP_HOST=http://192.168.1.170:8080/ # should change in run time.
    ports:
      - "8080:8080"
    #volumes:
    #  - /my/hitchhiker/public:/usr/src/Hitchhiker/build/public
    links:
      - hitchhiker-mysql:hitchhiker-mysql
  hitchhiker-mysql:
    image: mysql:5.7
    container_name: hitchhiker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hitchhiker888
      - MYSQL_DATABASE=hitchhiker-prod
    volumes:
      - ./hitchhiker-mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf
      - /my/hitchhiker/sqldata:/var/lib/mysql

你看看我这里是不是需要特别注意修改那个位置呢？  感觉之前就是因为数据库起不来才会没有反应吧？

**Comment by brookshi** [comment]
hitchhiker-mysql.cnf 这个文件有下载下来吗

**Comment by teddymail** [comment]
有的，下载下来了，在同目录中
[root@localhost hitchhiker]# cat hitchhiker-mysql.cnf 
[mysqld]
collation-server=utf8_general_ci
init-connect='SET NAMES utf8'
character-set-server=utf8
max_allowed_packet=200M
max_connections=1024

**Comment by brookshi** [comment]
好，你稍等下，我去试下

**Comment by brookshi** [comment]
你是在window下的虚拟机里面？

**Comment by teddymail** [comment]
我是通过虚拟机VMware虚拟的centos中，通过桥接的形式进行的安装，这个会影响么？

**Comment by brookshi** [comment]
看起来是，虚拟机里的目录不能自动创建

**Comment by teddymail** [comment]
你看我需要手动创建那些？ 我自己创建吧

**Comment by brookshi** [comment]
先这样试下，进到hitchhiker-mysql里，把hitchhiker-mysql.cnf文件放到/etc/mysql/conf.d/目录里再重启docker

**Comment by brookshi** [comment]
哦，docker现在起不来吧，先把docker-compose.yml里的 `- ./hitchhiker-mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf`这行删掉

**Comment by teddymail** [comment]
我启动后进入页面后还是无法进入主页面的问题
![image](https://user-images.githubusercontent.com/3467695/29811387-d8c0e922-8cd5-11e7-9b84-0e84b5838c19.png)

###docker 运行情况
[root@localhost hitchhiker]# docker ps
CONTAINER ID        IMAGE                        COMMAND                 CREATED             STATUS              PORTS                    NAMES
6055af9e2447        brookshi/hitchhiker:v0.1.1   "pm2-docker index.js"   9 seconds ago       Up 8 seconds        0.0.0.0:8080->8080/tcp   hitchhiker

**Comment by brookshi** [comment]
看起来还是数据库的问题，temp那个一直在pending, 在hitchhiker container里有个日志在logs目录下，看看那个，再不行的话我搭个环境试下

**Comment by teddymail** [comment]
我没有找到日志，我感觉docker没有启动mysql的感觉

**Comment by brookshi** [comment]
看这个： https://github.com/moby/moby/issues/26822  windows下虚拟机确实有这类问题，先不管hitchhiker-mysql.cnf文件吧，删除掉所有docker，把docker-compose.yml里的
```
volumes:
      - ./hitchhiker-mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf
      - /my/hitchhiker/sqldata:/var/lib/mysql
```
都删掉，再重装下看看

**Comment by teddymail** [comment]
root@localhost hitchhiker]# docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.hitchhiker-mysql.volumes contains an invalid type, it should be an array

发生以上问题，我想问docker中哪里是修改应用数据库配置的地方，我自己建立一个mysql吧，还有这个应用不用创建数据库表么？不需要执行安装数据库操作么？

**Comment by brookshi** [comment]
没删对呀  hitchhiker-mysql的volumes是不是没整个删掉。
自己建mysql没问题，前面issue也是这么干的。
创建数据库是在安装docker时创建的，表是程序启动时创建的。
我觉得可以考虑用源码安装，windows上虚拟机的docker不太靠谱

**Comment by teddymail** [comment]
我从将docker从新安装一遍，一切安装正常，mysql也已经启动了就是有个问题，我的ip是私有的，通过公网ip映射到私有上，docker 网桥地址 又是另一个，有没有好的解决方案？ 服务器使用阿里云ECS服务器，操作系统是centos

**Comment by brookshi** [comment]
这没什么问题呀，http://www.hitchhiker-api.com 也是在阿里云上，也是公网弹性ip映射到私有ip上，没什么问题

**Comment by teddymail** [comment]
我现在是按照linux单独安装的方式进行安装，发现登录注册时显示不存在这个api是怎么回事呢？

![image](https://user-images.githubusercontent.com/3467695/29904313-c9ed5be0-8e3a-11e7-85e2-0285a7a120c1.png)

**Comment by brookshi** [comment]
创建数据库是 hitchhiker-prod 要用 ` 号括起来（键盘上1左边的键），加我微信吧，iwxiaot， 有什么事情在微信上面直接问来得快

**Comment by brookshi** [comment]
刚看了下文档，本来是有写 ` 号的，不过MD转成了`hitchhiker-prod`这种。。，是我的错，回头改下

**Comment by lu007heng** [comment]
我清了cookie 重启了两个container 好了
