### ISSUE TITLE
部署完成后出现两个Stopped的module, 压力测试模块异常

### ISSUE THREAD

**Issue by yj950714** [brookshi/Hitchhiker#50]
- 在部署完成后，本地的基本测试可以运行，但是pm2显示有两个module是stop状态
![_20171116151912](https://user-images.githubusercontent.com/20449055/32878636-cd093cca-cae1-11e7-8a4e-7807e6cc251c.png)
请问他们的功能是什么

- 我运行了hitchhiker-node之后，street仍然不能运行，提示找不到node，是否和这两个模块有关呢？

**Comment by yj950714** [comment]
对了，hitchhiker-node的状态一直是这样的
![2](https://user-images.githubusercontent.com/20449055/32878837-9897e6a2-cae2-11e7-85d2-19ae3867d244.png)

**Comment by brookshi** [comment]
那两个module是pm2的依赖module，stress node连不上可以参考 https://github.com/brookshi/Hitchhiker-Node/issues/1

**Comment by yj950714** [comment]
- 那两个module是Stop状态对于hitchhiker运行有什么影响吗？
- node开启后可以连接，但是运行报错如下：
![3](https://user-images.githubusercontent.com/20449055/32879522-4c2d5a4c-cae5-11e7-8c10-b10ae236fd57.png)

**Comment by brookshi** [comment]
应该是没啥影响， 这个是stress暂时还没跟上web这边， 不支持pre request script和ES6，这是下一步要做的

**Comment by yj950714** [comment]
我尝试了一个简单的GET请求(一个链接，无参数，无pre requestscript)，使用Street后仍然是上面的结果，是不是也是因为即使普通请求也涉及到了ES6，所以目前Street还不能正常使用？

**Comment by brookshi** [comment]
test里有写吗

**Comment by yj950714** [comment]
没有写东西

**Comment by brookshi** [comment]
那确实奇怪，我回去测试下，发布前是有试过是可以的

**Comment by yj950714** [comment]
这是配置和运行情况和node运行窗口的log
![1](https://user-images.githubusercontent.com/20449055/32927429-710f2032-cb87-11e7-94c7-74c5671ec121.png)
![2](https://user-images.githubusercontent.com/20449055/32927432-753d21f4-cb87-11e7-9cc8-09e6f83a5342.png)
![3](https://user-images.githubusercontent.com/20449055/32927436-78d5d86a-cb87-11e7-8b86-218619e8aea7.png)

**Comment by brookshi** [comment]
不好意思哈，昨天太忙了，没来得及看。
有点奇怪为啥老是连接失败，看过程是发了几次结果后就连接失败，再重连，再连接失败

**Comment by brookshi** [comment]
看下Hitchhiker/logs里的日志，或者贴上来我看下，可能是有什么异常导致服务把压力测试的进程关掉，从而导致压力点的连接失败

**Comment by yj950714** [comment]
![1](https://user-images.githubusercontent.com/20449055/32931095-49f29784-cb9d-11e7-8a00-8f1a533f54f2.png)
中间总是有个Warning，把Stress exit掉

**Comment by brookshi** [comment]
确实是stress进程被干掉了，不过也不知道原因，log少写了点

**Comment by brookshi** [comment]
也没看到有什么异常，电脑上是不是有什么在杀进程呢，比如杀毒软件之类

**Comment by brookshi** [comment]
不过也奇怪，我本地pm2 list all 并没有你上面那两个module 
![image](https://user-images.githubusercontent.com/13607728/32931909-a6d1451e-cba1-11e7-82fc-bfea16ff6b7f.png)

**Comment by brookshi** [comment]
是我的错，刚发的一个小版本0.4.1里带进来的，node8 引入了新的setInterval,  作死前面加了个window，导致异常，明天发0.4.2修复，抱歉。

**Comment by brookshi** [comment]
v0.4.2 发布，请更新下
