### ISSUE TITLE
使用过程中发现对于自签名的证书不认，很多没法测试，能给个建议么？

### ISSUE THREAD

**Issue by lucas-sre** [brookshi/Hitchhiker#51]
目前自己测试内部的项目都是自签名证书，不知道能在这个测试工具的代码层面上怎么修改下，能够通过我的自签名证书

**Comment by brookshi** [comment]
呀，这个是想下个版本加个setting来控制的，现在要改的话只能改下代码了，如下：
Hitchhiker\build\run_engine\record_runner.js 文件 177 行，换成下面：然后重启pm2
```js
const res = yield RecordRunner.request({...option, strictSSL: false}, serverRes, needPipe);
```

**Comment by brookshi** [comment]
解决，在Collection的菜单下加了一项：`Request Strict SSL`，勾上的话才会检查SSL证书是否合格，默认为false
