### ISSUE TITLE
FAILSyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by mikuazusa** [brookshi/Hitchhiker#52]
在接口用例里使用Test功能出现异常报错，重装了几次也是一样的情况。
下图执行的是自带的sample get用例，接口请求、返回都是正常的，只有test执行报错：

tests["Status code is 200"] = responseCode.code === 200;

tests["request is success"] = responseObj.success;

tests["id is correct"] = responseObj.result.id === "001";

![image](https://user-images.githubusercontent.com/2417904/32939487-9f3e1390-cbba-11e7-9f1d-13e34911debe.png)

**Comment by brookshi** [comment]
change log里忘了提示要更新下node了，只在文档里更新了，不好意思，因为在脚本里支持使用async/await，所以 node需要在7.6以上，最好是最新的LTS版 8.9，参考[文档](https://github.com/brookshi/Hitchhiker/blob/master/doc/howtoinstall-linux-cn.md)

**Comment by mikuazusa** [comment]
thx，更新node版本后问题已解决。
