### ISSUE TITLE
Failed to construct 'WebSocket': The URL 'wsststresstest' is invalid.

### ISSUE THREAD

**Issue by sblig** [brookshi/Hitchhiker#55]
http://localhost:8000/

    initStressWS(dispatch: Dispatch<any>) {
        this.dispatch = dispatch;
        this.socket = new WebSocket(Urls.getWebSocket('stresstest')); // error
  })

**Comment by brookshi** [comment]
这块是有点问题，socket失败后应该去重连下，现在只能刷新浏览器来重连

**Comment by brookshi** [comment]
@sblig 已经修复，失败后自动重连

**Comment by wujohns** [comment]
依旧有这样的问题，刷新浏览器后一直出现

**Comment by wujohns** [comment]
回到了0.8版本就都正常了，0.9的话除了前端的报错提醒外，后端日志中也有mysql连接池的相关错误

**Comment by brookshi** [comment]
@wujohns 因为会尝试重连压测服务，如果服务没起来就会一直有错误信息，mysql连接池的错误没碰到过，下次碰到麻烦传下日志，：）谢谢
