### ISSUE TITLE
runPreScript before parsing parameters?

### ISSUE THREAD

**Issue by menzow** [brookshi/Hitchhiker#57]
Hey,

First of all - what a amazing  piece of software. Great built quality and documentation. 👍 

For my use case I'm looking to automatically test certain API endpoints with a set of valid and invalid parameters. Using ManyToMany parameters I can run the required tests with minimal overhead. For interoperability I'd like to store my ManyToMany parameters in a separate json/xlsx file.

After some trial and error and no success I checked the code to see if this is possible through scripting. My understanding is that the [`RecordRunner::runRecordWithVW`](https://github.com/brookshi/Hitchhiker/blob/8404e174d93f486674f114a1fbeea067a84b0f85/api/run_engine/record_runner.ts#L86) method is responsible for evaluating the [pre request script](https://github.com/brookshi/Hitchhiker/blob/8404e174d93f486674f114a1fbeea067a84b0f85/api/run_engine/record_runner.ts#L93) and executing the http request. For records with a ManyToMany parameter type this method is called in a loop. ([`RecordRunner::runRecordSeries`](https://github.com/brookshi/Hitchhiker/blob/8404e174d93f486674f114a1fbeea067a84b0f85/api/run_engine/record_runner.ts#L47))

Is it possible to modify records before RecordRunner::runRecordSeries is called? This would allow me to set the necessary record parameter values with readFile.

I managed to cover my use with a stress test that concurrently checks all the validation entries and repeats requests just once. The uncontrolled load makes this a hacky solution.

**Comment by brookshi** [comment]
Hi menzow,

Yes, you're right.
According to this [request's flow chart](http://doc.hitchhiker-api.com/en/Script/) , Script will not apply to parameters.

Seem there is no way to do it in current build 0.5. And in 0.6 I will improve stress test to support Script API.

So I will support this requirement in 0.7 which will be released after about 3-4 weeks.

**Comment by menzow** [comment]
Hey @brookshi,

But that configures just a single request right? The amount of requests created depends on the parameters parsed in the build phase. I'd like to control the parameters through separate file for more interoperability.

If you have any ideas on how to achieve this and it's not yet possible I'd be up for implementing the feature.

**Comment by menzow** [comment]
Hey @brookshi , below you can view the result of my test.


Pre request script:
```hitchhiker.setEnvVariable("b", [1,2,3,4,5]);```

Request Configuration:
![Uploading Screen Shot 2017-12-09 at 06.00.12.png…]()

**Comment by brookshi** [comment]
Yes, variable is only vaild for single value in parameters.

It's easy to apply array in `::recordRunner`, But as you say, `{"a" : {{b}} }` will break the UI and you can't select any param in drop down list.

I have no idea how to handle this in UI, do you have any good suggestion?

**Comment by menzow** [comment]
No. To resolve the parameters within the wysiwyg editor will be unnecessarily difficult I think. 

The ParameterType seems great for cleanly separating business logic. My idea is to add a new type: `JsonFile`. That makes it possible to show the wysiwyg editor for OneToMany/ManyToMany and a ProjectFiles dropdown for the JsonFile type. parseParameters just needs to read the selected file, the returned data structure could stay the same.

Conceptually the way parameters are implemented they could provide a rich data object to pre run scripts that would allow many new use cases. For me personally this is very useful but I'm not sure if this is within the intended scope.

**Comment by brookshi** [comment]
`JsonFile` is really a good idea. I'll go along with you.

One point to be aware of is that the response panel should have a way to display a sub request's response:  add a link for each response or add a response dropdown.

**Comment by menzow** [comment]
Hey @brookshi,

I haven't been able to produce something useable for this yet. Sorry for the delay. I see you added a milestone to the issue, did you start implementing this?

**Comment by brookshi** [comment]
Hey, I'm not implementing this yet, but I had improved request workflow in v0.6 like [this](http://doc.hitchhiker-api.com/en/Script/). In the split phase, runtime variables will apply to parameters.
So if you set a parameters variable in runtime, and then use it in another request, this parameters will work.

I add a sample collection in [www.hitchhiker-api.com](www.hitchhiker-api.com) named `runtime parameters`, it has two requests: `prepare` which used to generate parameters in pre-request-script and `run` which has a variable in parameters. Then in Schedule, you can see the parameters work as expect.

use email: `test@test.test`, password: `123456` to login.

I think this way can resolve a problem: sometimes the parameters must be generated in runtime but not a file that uploaded before.

What do you think? Waiting for your reply。

**Comment by brookshi** [comment]
😴

**Comment by brookshi** [comment]
Hey @menzow,
v0.7 which support parameters as a variable is released, does it meet your requirement.
