### ISSUE TITLE
docker版本的日志在什么地方？

### ISSUE THREAD

**Issue by Huarong** [brookshi/Hitchhiker#58]
我用docker 镜像 v0.5安装，发现启动失败了，想看看错误日志，用 docker logs 命令什么都看不到

**Comment by brookshi** [comment]
参考：[http://blog.csdn.net/halcyonbaby/article/details/47336269](http://blog.csdn.net/halcyonbaby/article/details/47336269)， 
docker logs 后面要加容器名

**Comment by Huarong** [comment]
我的意思是 `docker logs d5049d7e48cc` 返回的内容就是空。所以问问你是不是有其他路径存储了启动日志

**Comment by brookshi** [comment]
没有，程序日志在container里面，按道理启动不起来docker logs应该有些错误日志的，我这边docker 0.5是可以运行起来的

**Comment by Huarong** [comment]
你的docker logs 有内容吗？我也不确定是否启动成功了，反正访问 curl http://localhost:port 失败

**Comment by brookshi** [comment]
有内容，试下 sudo docker ps，看是否有在运行，有的话就sudo docker exec -it 容器id bash，进到容器里面，再运行 pm2 status 看看是否在运行

**Comment by Huarong** [comment]
![image](https://user-images.githubusercontent.com/1487879/33825913-20fd1c78-de9e-11e7-906e-ac42b7eeec73.png)

**Comment by brookshi** [comment]
这看起来是正常运行的

**Comment by Huarong** [comment]
返回空：

    $ docker logs d5049d7e48cc

连接的时候被重置：

    $ curl http://localhost:7765
    curl: (56) Recv failure: Connection reset by peer

**Comment by Huarong** [comment]
应该是我自己的问题，我所有的 容器都看不到日志了，谢谢
