### ISSUE TITLE
数据库错误

### ISSUE THREAD

**Issue by eeokee** [brookshi/Hitchhiker#59]
你好，发现一个Bug

关联指定项目A的用户登陆时出现此错误
![2](https://user-images.githubusercontent.com/3079825/33758169-2c8d4f6c-dc38-11e7-9e5b-938d4149611a.png)

pm2日志
![1](https://user-images.githubusercontent.com/3079825/33758170-2ce1d834-dc38-11e7-86cb-7c5f718919c8.png)

新注册了一个用户，可以正常登陆，数据库手动添加关联指定项目A，则一样不能登陆，其他账户删除关联项目A后也可以登陆。

环境：Win10 x64
项目已经正常运行1个多月

**Comment by brookshi** [comment]
好的，我会尽快看下

**Comment by brookshi** [comment]
异常信息少了点，看下Logs目录下的Log有没有详细些的

**Comment by brookshi** [comment]
猜测应该是request或者schedule记录里有些字符被JSON.parse识别不了，mysql有用utf8吗

**Comment by eeokee** [comment]
@brookshi 你好，日志文件已发到你的邮箱。

**Comment by brookshi** [comment]
收到 ，大概看了下，应该是schedule里的记录里有些图片之类的返回结果导致做JSON.parse时出错，workaround是你不介意schedule跑的记录的话，可以先把记录清掉（在schedulerecord表里， 相关的collectionid是"057a53b0-9daf-11e7-bb66-43fe5c70be45-S1avOL1oZ","03f25280-96bc-11e7-a4bd-313ee5639ad4-B1xpJ2mcb"这两个），然后把找到返回image或zip这类二进制的request先移出collection，或者不介意的话发给我，我再尝试在我这边重现下。

**Comment by eeokee** [comment]
@brookshi 确实是schedule_record 记录的问题，我把该表清空后可以使用了。随后再次执行schedule复现了错误，已把该表数据发到你的邮箱。所请求的接口中有返回image二进制数据。

**Comment by brookshi** [comment]
看了下，确实是image的数据导致的，里面包含了一些json符号，导致整个json没法parse，你可以先把schedule record清一下，然后把取图片的api移出这个collection，我下个版本会把取图片的数据过滤掉，不存到schedule record里

**Comment by eeokee** [comment]
@brookshi OK

**Comment by brookshi** [comment]
@eeokee 问题修复了，图片会保存到数据里，只保存了链接
