### ISSUE TITLE
windows下的docker部署，部署完成后使用功能

### ISSUE THREAD

**Issue by orzcncn** [brookshi/Hitchhiker#6]
如图
![image](https://user-images.githubusercontent.com/8609626/30020495-9115ffc0-9196-11e7-932a-be31c8e74faa.png)

卡在这步，搜索引擎查找提示好像是js的问题？请问大佬有遇到过这个问题么

**Comment by brookshi** [comment]
win下的docker貌似是有些问题，这个提示是js的，不过原因可能是数据库的，是用的docker的toolbox吗？
麻烦先抓个浏览器控制台的图看下

**Comment by orzcncn** [comment]
是使用公司的win10电脑运行的docker呢，明天去到公司把控制台的图截给你，好像是api那个接口的问题

**Comment by brookshi** [comment]
好，可以加我微信 iwxiaot，方便沟通

**Comment by orzcncn** [comment]
更新docker for windows后，使用localhost:8080访问正常了
