### ISSUE TITLE
POST 请求中鉴权用的 token 如果放在 cookie 里面，请求会失败

### ISSUE THREAD

**Issue by wangyunshuai** [brookshi/Hitchhiker#60]
版本：0.5
系统：CentOS 7
部署方式：docker

问题：
headers:
Content-Type: application/x-www-form-urlencoded
Cookie: xxxxxxxx

POST 请求时，如果需要鉴权的 token 放到 cookie 中，服务器不能获取。

使用 postman 时，不开启 interceptor 也会失败，开启后能成功。

**Comment by brookshi** [comment]
Hitchhiker倒是会对cookie做些处理，我测试下看看，稍等会再答复。

**Comment by brookshi** [comment]
调试了下，Cookie是有发送过去的
![image](https://user-images.githubusercontent.com/13607728/33836789-6d9affb0-dec5-11e7-94d0-9f71b54663d3.png)
看是不是有哪里做得不一样

**Comment by brookshi** [comment]
Hitchhiker会把当前domain下的cookie和collection下的cookie以及写在header里的cookie都发给server

**Comment by wangyunshuai** [comment]
postman 中，body 的写法使用 x-www-form-urlencoded 可以成功，如果使用 raw 写 json 格式会失败。

在 postman 中，我再 body 中使用x-www-form-urlencoded 和 raw(json)两种格式写的请求分别导出来：
x-www-form-urlencoded 格式的导入到 hitchhiker 后，发现 body 下是空的。可能说明了一点问题。

**Comment by brookshi** [comment]
哦，那是不是server不支持json的body呀，或者你的body是json的话，header里需要加上content-type:application/json。因为form-urlencoded的body格式是不一样的。

**Comment by wangyunshuai** [comment]
如果服务端只支持 form-urlencoded 格式怎么办呢？

**Comment by wangyunshuai** [comment]
hitchhiker 能支持吗？

**Comment by brookshi** [comment]
那就在body里写这个格式的，比如你把postman抓包下来的body直接写到hitchhiker的body里面

**Comment by brookshi** [comment]
应该是`a=b&c=d`类似的格式吧

**Comment by wangyunshuai** [comment]
我试下

**Comment by wangyunshuai** [comment]
可以了。

确实需要 a=b&c=d 这种格式的。非常感谢

**Comment by brookshi** [comment]
不客气：）

**Comment by wangyunshuai** [comment]
没有计划做这个功能吗？
![form](https://user-images.githubusercontent.com/12732404/33838614-f801c580-deca-11e7-9f53-208198523c79.png)

**Comment by brookshi** [comment]
是有的，可以在 [task.todo](https://github.com/brookshi/Hitchhiker/blob/master/tasks.todo)里的backlog里有看到，不过因为body也能实现这个功能，只是用上去没那么方便，所以优先级还不高

**Comment by wangyunshuai** [comment]
明白了
