### ISSUE TITLE
pre request Script  中的环境变量，怎么使用在request 的body中？

### ISSUE THREAD

**Issue by da-peng** [brookshi/Hitchhiker#62]
我在pre request Script中  
```
hitchhiker.setEnvVariable("sign_", getSignature());
```
设置了sign_
需要在body json Request 中使用，我试着用{{}} 发现不能实现

**Comment by da-peng** [comment]
或者有其它的方式

**Comment by brookshi** [comment]
我试了下是没有问题的，如果是字符串，你需要加上引号，{{sign_}}是纯粹替换成具体的值

**Comment by da-peng** [comment]
不能使用方法getSignature()？

**Comment by da-peng** [comment]
header 中也可以使用{{ }}来引用参数吗？

**Comment by brookshi** [comment]
getSignature()这个方法你有定义吗，内置没有这方法，需要获取sign的话可以使用内置的库crypto-js或者uuid，具体使用参考 [文档](http://doc.hitchhiker-api.com/cn/Script/API.html)，header同样可以使用变量

**Comment by da-peng** [comment]
@brookshi 
![](https://public.lightpic.info/image/C2BA_5A3092AE0.jpg)
我在Body 中json请求内容设置了，请求的时候就我抓的报文，看到传的是{{id_}}

**Comment by brookshi** [comment]
我建了个例子在 [www.hitchhiker-api.com](www.hitchhiker-api.com)，用户名 `test@test.test` 密码`123456` ， Sample Collection下面有个 `environment` request，可以看下这个，请求之后这个url会把你发送的内容都返回来，看response就知道发了哪些

**Comment by brookshi** [comment]
猜测你可能抓的是原始的内容，具体应用变量的过程是在服务端

**Comment by da-peng** [comment]
找到原因了，晕死，我方法写错了，可以在里面 console.log() 调试吗？～谢谢耐心指导🙏👍🏻，这工具好棒

**Comment by brookshi** [comment]
:smile: 调试暂时还没有太好的办法，我也有这个打算把运行过程返回给客户端，现在可以通过tests来作些简单调试，比如你的那个方法，在test里写tests[getSignuration()] = true，这样在response的test里就可以看到结果

**Comment by da-peng** [comment]
tests[getSignature()] = true，这种方式好像也是能调试，getSignaturn()方法定位在global function中，而且我好像发现一个问题，project的global function 写好save之后，这时候去request一个请求，再回去打开global function 显示是空的

**Comment by brookshi** [comment]
还真是，是个bug，下个版本修复，谢谢

**Comment by brookshi** [comment]
调试不方便可以单独提个支持console.log的需求，我回头有时间会实现它

**Comment by da-peng** [comment]
辛苦了，可以考虑开一个 支付宝点赞渠道👍🏻🤡🤡

**Comment by brookshi** [comment]
:smile: 有心支持已经非常感谢了，不过我倒是想建个群，下个版本发布的时候把群的二维码放上来，这样勾通会方便些

**Comment by brookshi** [comment]
@da-peng  global function的bug解决了，欢迎使用：）
