### ISSUE TITLE
能不能支持多组或者所有collections一齐手动运行跑一次，并且有一个汇总的结果报告

### ISSUE THREAD

**Issue by MattGong** [brookshi/Hitchhiker#64]
能不能支持多组或者所有collections一齐手动运行跑一次，并且有一个汇总的结果报告，或者一齐运行完后有问题的collection上有些明显示的提示？

**Comment by brookshi** [comment]
在Schedule加个Run all的功能，然后失败的Schedule在列表上显示一个红色标记，这样能否满足你的需求。

**Comment by MattGong** [comment]
感觉应该可以。 case多了有时想一起全部运行一下，看看效果。

**Comment by brookshi** [comment]
ok. 会加到计划中

**Comment by brookshi** [comment]
v0.8 fixed
