### ISSUE TITLE
如何停止压力测试

### ISSUE THREAD

**Issue by qianlei90** [brookshi/Hitchhiker#67]
v0.6版本中，是不是还不能停止压力测试？只看到`run now`、`edit`和`delete`。

![image](https://user-images.githubusercontent.com/5654791/34205994-974a6372-e5bf-11e7-8439-90db1c8183bb.png)

**Comment by brookshi** [comment]
暂时还没有，后面会加进来

**Comment by brookshi** [comment]
v0.8 fixed

**Comment by conglin-ruijie** [comment]
怎么手动关闭
