### ISSUE TITLE
[Solved]TypeError: Failed to fetch

### ISSUE THREAD

**Issue by wallezhang** [brookshi/Hitchhiker#68]
When i click "try without login", an error has occurred.

Deploy hitchhiker with docker but mysql is standalone. Edit appconfig.json `db` config.

**Comment by wallezhang** [comment]
Solved! Set ENV `HITCHHIKER_APP_HOST` is worked for me.

**Comment by Vickey-Wu** [comment]
你好！我想在docker-compose.yml同时启动hitchhiker，hitchhiker-mysql，hitchhiker-nginx，用hitchhiker-nginx代理访问hitchhiker，我在nginx的配置文件default.conf填写了hitchhiker容器的ip，虽然启动了，但是报错“TypeError: Failed to fetch”，我知道“HITCHHIKER_APP_HOST”这个字段填写公网就不会报错，有能用hitchhiker-nginx代理访问hitchhiker并不会报错的办法吗？
