### ISSUE TITLE
如何将上一个请求返回值作为下一个请求的参数？

### ISSUE THREAD

**Issue by fanhuaqa** [brookshi/Hitchhiker#69]
如何将接口返回的值如id，token作为全局变量传递给其他接口使用？

**Comment by brookshi** [comment]
这个很容易就可以实现，参考文档：[http://doc.hitchhiker-api.com/cn/Script/API.html](http://doc.hitchhiker-api.com/cn/Script/API.html)
在Test里使用hitchhiker.setEnvVariable(key, value)函数保存变量，然后在其他接口使用 {{key}}来使用

**Comment by fanhuaqa** [comment]
不知道接口返回的值如id，token，通过哪个函数可以提取？

**Comment by brookshi** [comment]
在Test里有responseObj这个是整个返回结果的json对象，可以用这个拿

**Comment by brookshi** [comment]
参考： [http://doc.hitchhiker-api.com/cn/Script/Test.html](http://doc.hitchhiker-api.com/cn/Script/Test.html)

**Comment by fanhuaqa** [comment]
请问responseObj的格式以及引用方法？
<img width="652" alt="image" src="https://user-images.githubusercontent.com/29515795/34479025-3e76ff9c-efdf-11e7-85b8-47af94585d95.png">

**Comment by brookshi** [comment]
不是这样的哦，responseObj.data.token就是token的值了，直接 `const token = responseObj.data.token` 就可以了

**Comment by fanhuaqa** [comment]
谢谢你的耐心解答，问题还没解决，其实我不是很确定token值是在responseObj.data.token可以取到么？用这样就不用setEnvVariable函数了对吗？项目首页的微信群二维码过期了，谢谢！

**Comment by brookshi** [comment]
谢谢提示，我更新下：）， 你的请求返回来的json是什么样呢，可以用console.log(responseObj.data.token)，浏览器控制台会显示结果

**Comment by brookshi** [comment]
二维码更新了

**Comment by fanhuaqa** [comment]
返回的是这样 
<img width="209" alt="image" src="https://user-images.githubusercontent.com/29515795/34481181-975f5666-efeb-11e7-8032-2d1afb786273.png">

**Comment by brookshi** [comment]
那应该是可以这样取token的

**Comment by brookshi** [comment]
console.log打印出来看看

**Comment by brookshi** [comment]
fixed. Schedule里的requests如果有依赖关系，需要勾上sort request并做好排序。
