### ISSUE TITLE
我在本地搭建了这个工具，注册时提示说没有注册这个API

### ISSUE THREAD

**Issue by sos3443** [brookshi/Hitchhiker#7]
求解决啊

PS.我是调研一下这个BS版本的postman，看看能不能做接口自动化用

**Comment by brookshi** [comment]
请先说明下是当前的环境(win还是linux)，用的是docker还是源码部署，另外抓下浏览器控制台的错误信息，方便知道什么问题。
确实可以认为是BS版的postman的pro版了，其实postman也是js写的，这个工具的最初目的就是接口自动化，只是不知道符不符合你要求，我们现在用在uat与product的环境的数据对比。

**Comment by foreverwing99** [comment]
你好，我使用的是mac电脑，采用的是源码部署方式，在浏览器中输入的url为：http://127.0.0.1:8080/，我点击了“try without login”遇到了"this api does not exist的问题"。
![image](https://user-images.githubusercontent.com/28041107/30213208-a11af2d0-94da-11e7-85de-11892a28d753.png)，请求大神帮忙看一下。
![image](https://user-images.githubusercontent.com/28041107/30213252-d69ac20a-94da-11e7-8a95-ff293e451755.png)
![image](https://user-images.githubusercontent.com/28041107/30213262-de6e0c30-94da-11e7-8c9f-d3c12199bf61.png)

**Comment by brookshi** [comment]
刚有朋友碰到类似问题，可能和你这差不多，可以参考下： https://github.com/brookshi/Hitchhiker/issues/8#issuecomment-328252029
