### ISSUE TITLE
协作性呢？可以先中文？

### ISSUE THREAD

**Issue by liutf** [brookshi/Hitchhiker#70]
介绍里说支持团队协作，看了下，没找到。。

请问是怎么协作的？能否文档里也体现下。

 另，能先默认中文吗？没多少个词，后续再做成国际化吧，先母语还是舒服一点。

 看过N多api接口工具了，看好你们。

**Comment by brookshi** [comment]
谢谢支持，协作性方面文档确实没怎么写。

协作的话比如在Hitchhiker你可以为你的team的项目建立一个Project，然后在Project里邀请team的成员，这样每个成员就能看到所有人建立在这个Project下的case，一起来维护同一份case，request支持查看成员修改的记录，另外还可以支持自动同步修改（默认关闭）：http://doc.hitchhiker-api.com/cn/other.html

中文的话是有打算的，大概不久就会支持吧。
