### ISSUE TITLE
安装后无法打开，步骤见图

### ISSUE THREAD

**Issue by fastluo** [brookshi/Hitchhiker#73]
mac 系统
安装包安装
![image](https://user-images.githubusercontent.com/31495325/35080243-442e2ce8-fc47-11e7-8062-a3041f6f10d8.png)
![image](https://user-images.githubusercontent.com/31495325/35080260-53c14bd6-fc47-11e7-9dc8-6ed1d17050fe.png)
后续都默认
![image](https://user-images.githubusercontent.com/31495325/35080276-69a6cb2e-fc47-11e7-92fd-7e1ebf8ac4cd.png)

**Comment by brookshi** [comment]
node setup.js 命令行那里有输出什么吗

**Comment by fastluo** [comment]
@brookshi 
![image](https://user-images.githubusercontent.com/31495325/35082408-9e87246c-fc54-11e7-8160-6fd7776f5781.png)
没有输出
