### ISSUE TITLE
浏览器打开一会就运行缓慢，是哪地方配置问题吗

### ISSUE THREAD

**Issue by fastluo** [brookshi/Hitchhiker#75]
系统 mac
浏览器 chrome和火狐都试了  
![image](https://user-images.githubusercontent.com/31495325/35087354-e244f25e-fc6a-11e7-9ece-b1ce5c14813a.png)
这是火狐的提示

是不是saveFile 后 一定要removeFile 

是不是要关闭调试模式 。。。

**Comment by brookshi** [comment]
这我倒是第一次碰到，saveFile并不一定需要remove，这不会影响前端，你一直开着F12吗，是否有安装react插件之类

**Comment by fastluo** [comment]
@brookshi 嗯 开着F12，插件没安装，原始包
接口中做302 跳转 ，会不会有这样的问题

**Comment by fastluo** [comment]
试了下 打开F12，点2下 就卡死了，不开的话 没啥大问题
![image](https://user-images.githubusercontent.com/31495325/35091780-81e4a8e2-fc78-11e7-98a7-217e52dcc8bc.png)

**Comment by fastluo** [comment]
试了下 打开F12，点2下 就卡死了，不开的话 没啥大问题

**Comment by brookshi** [comment]
好像是有些浏览器版本会这样，我这边倒还好，开发经常开着F12，很少碰到，网上查了下说是React插件的问题，但看你那好像没装这个插件，也是有点奇怪。

**Comment by fastluo** [comment]
@brookshi 好的 我再跟踪下 试试
