### ISSUE TITLE
V8 创建Project 修改名称用中文，无法同步。

### ISSUE THREAD

**Issue by zhangmz0223** [brookshi/Hitchhiker#77]
1. 使用中文，无法自动同步(如下图)。
2. form data 好像没有支持不够？ 

![image](https://user-images.githubusercontent.com/10662992/35133440-1f10aad4-fd0b-11e7-92fc-707a0149cfcd.png)

**Comment by brookshi** [comment]
不能同步应该是后端有什么问题，你的数据库有没有设置utf8
formdata现在确实没有ui上的支持，只能先在body里写 a=1&b=2 了

**Comment by zhangmz0223** [comment]
用的是你的docekr-compose。
有可能是没设置UTF-8
