### ISSUE TITLE
怎么上传文件，文档没看到哇

### ISSUE THREAD

**Issue by fastluo** [brookshi/Hitchhiker#78]
怎么上传文件，文档没看到哇

**Comment by brookshi** [comment]
脚本 ： http://doc.hitchhiker-api.com/cn/Script/custom-javascript-lib.html
数据： http://doc.hitchhiker-api.com/cn/Script/custom-data-file.html
API： hitchhiker.saveFile

**Comment by fastluo** [comment]
@brookshi 速度杠杠的 ☺
