### ISSUE TITLE
this api does not exist的问题

### ISSUE THREAD

**Issue by foreverwing99** [brookshi/Hitchhiker#8]
你好，我使用的是mac电脑，采用的是源码部署方式，在浏览器中输入的url为：http://127.0.0.1:8080/，我点击了“try without login”遇到了"this api does not exist的问题"。
![image](https://user-images.githubusercontent.com/28041107/30213208-a11af2d0-94da-11e7-85de-11892a28d753.png)，请求大神帮忙看一下。
![image](https://user-images.githubusercontent.com/28041107/30213252-d69ac20a-94da-11e7-8a95-ff293e451755.png)
![image](https://user-images.githubusercontent.com/28041107/30213262-de6e0c30-94da-11e7-8c9f-d3c12199bf61.png)

**Comment by foreverwing99** [comment]
我进行注册的时候也遇到一样的问题，请求帮助。

**Comment by brookshi** [comment]
你好， 是url不对，看起来myhost没被替换掉，麻烦贴下Hitchhiker目录下的pm2.json文件内容

**Comment by foreverwing99** [comment]
![image](https://user-images.githubusercontent.com/28041107/30236544-8fe851aa-954e-11e7-85e6-e40674ba1f74.png)
是这个文件吗？

**Comment by brookshi** [comment]
是的，确实没换掉， linux_deploy.sh里的myhost是有换掉吧

**Comment by foreverwing99** [comment]
![image](https://user-images.githubusercontent.com/28041107/30236561-cfc2708a-954e-11e7-9560-7cd7ddd88b31.png)
换成我的电脑的ip地址是吗哈？

**Comment by brookshi** [comment]
对的，看起来是我的脚本写得有点问题，sed -i 's/myhost/$'myhost'/g' pm2.json 这行没起作用，奇怪我在ubuntu上试了是可以的，我去mac上试一下

**Comment by foreverwing99** [comment]
嗯嗯 好的好的，谢谢你哈

**Comment by brookshi** [comment]
着急用的话可以改下 Hitchhiker/build/public/static/js/main.**.js， 找到 myhost，换成ip:port，然后在Hitchhiker目录下运行命令 `pm2 skill &  pm2 start pm2.json`

**Comment by brookshi** [comment]
不客气，是我的问题

**Comment by foreverwing99** [comment]
好的 好的 ，谢谢哈～～～你share的工程对我帮助很大呢～～～嘿嘿

**Comment by foreverwing99** [comment]
我刚接触软件不是很多，刚刚搜索了一下，并在我电脑上新建了一个小文件试了一下，似乎生效。

`问题一
sed编辑命令：【sed -i ‘s/a/b/g‘ test.txt】
 
报错：sed: 1: "test.txt": undefined label ‘est.txt‘
 
解决方案：增加一个备份的追加名【sed -i ‘.bak‘ ‘s/a/b/g‘ test.txt】
 
原因：mac强制要求备份，否则报错
当然可以不使用其他备份名字，只是用’‘，就可以只保留一份
sed -i ‘’ ’s/a/b/g’ test.txt`

**Comment by brookshi** [comment]
是的，我刚在mac上试了下，用 `sed -i '' "s~myhost~$myhost~g" pm2.json`  就可以了，我改下

**Comment by brookshi** [comment]
mac 是 基于BSD的unix，sed命令与linux不太一样

**Comment by foreverwing99** [comment]
嗯嗯 感觉你知识好渊博，我对linux命令和nodejs几乎一无所知，正在努力学习你的东东，要加油加油努力才行～～～

**Comment by brookshi** [comment]
哈哈，过奖了，我也是杂七杂八的学，都不精通，更新了脚本和文档，不过没找到两类系统都可以用的脚本，所以在mac上需要替换下sed那行

**Comment by foreverwing99** [comment]
你好，我用“sudo sh linux_deploy.sh”替代“source ./linux_deploy.sh”这个命令可以吗？因为我用“source ./linux_deploy.sh”这个命令的时候会报错很多权限不足，且我在前面加sudo也会报错，所以我用“sudo sh linux_deploy.sh”这个命令，但是在登陆的是sign in一直在转圈，登陆不进去，下面的console也没有报错，不知道是怎么回事

**Comment by brookshi** [comment]
数据库问题，因为存了column为json的字段，mysql需要5.7+版本。
