### ISSUE TITLE
请求接口 图片验证码  为什么同时发起了2次请求

### ISSUE THREAD

**Issue by fastluo** [brookshi/Hitchhiker#81]
F12看是一次，但是服务端接收到了2次请求，不知道什么原因

**Comment by brookshi** [comment]
正常是不会的，我这边调试代码没发现有这情况

**Comment by brookshi** [comment]
你脚本里有没有去调相关接口

**Comment by fastluo** [comment]
@brookshi 
接口直接返回的是一个  'Content-Type: image/png' ，输出直接是图片，你再测试下

**Comment by fastluo** [comment]
`header ('Content-Type: image/png');
$image=imagecreatetruecolor(100, 30);
//背景颜色为白色
$color=imagecolorallocate($image, 255, 255, 255);
imagefill($image, 20, 20, $color);
// for($i=0;$i<4;$i++){
// $font=6;
// $x=rand(5,10)+$i*100/4;
// $y=rand(8, 15);
// $string=rand(0, 9);
// $color=imagecolorallocate($image, rand(0,120), rand(0,120), rand(0,120));
// imagestring($image, $font, $x, $y, $string, $color);
// }
$code='';
for($i=0;$i<4;$i++){
	$fontSize=8;
	$x=rand(5,10)+$i*100/4;
	$y=rand(5, 15);
	$data='abcdefghijklmnopqrstuvwxyz123456789';
	$string=substr($data,rand(0, strlen($data)),1);
	$code.=$string;
	$color=imagecolorallocate($image,rand(0,120), rand(0,120), rand(0,120));
	imagestring($image, $fontSize, $x, $y, $string, $color);
}

for($i=0;$i<200;$i++){
	$pointColor=imagecolorallocate($image, rand(100, 255), rand(100, 255), rand(100, 255));
	imagesetpixel($image, rand(0, 100), rand(0, 30), $pointColor);
}
for($i=0;$i<2;$i++){
	$linePoint=imagecolorallocate($image, rand(150, 255), rand(150, 255), rand(150, 255));
	imageline($image, rand(10, 50), rand(10, 20), rand(80,90), rand(15, 25), $linePoint);
}
imagepng($image);
imagedestroy($image);
`

php 生成验证码代码

**Comment by brookshi** [comment]
哦，想起来了，请求如果返回的是图片的话，内容会丢掉不要，直接在网页上显示一个img，应该是这个img本身又请求了一次，这应该没什么关系吧

**Comment by fastluo** [comment]
估计有关系  ，你试下， 我这边现在这种情况就是服务端接到2次发来的请求

**Comment by brookshi** [comment]
哦，你那个还要cookie呀，这确实会比较麻烦，因为第2次是浏览器自己发出的，可能没有cookie。之前这样做的目的是取回来显示的话会把图片数据存到数据库里，因为是二进制，解析成json的时候有问题。你这种情况我得再想想办法。

**Comment by fastluo** [comment]
这个bug修复有日程计划吗，现在因为这个我登录走不下去了

**Comment by brookshi** [comment]
这会影响登录吗，第二次会再拿一个无效的cookie回来？，如果这样，可以绕过去，在请求的test里从responseHeader里把cookie拿出来给其他请求用

**Comment by brookshi** [comment]
等我想好解决方案会尽快解决，想到了会在这里更新下

**Comment by brookshi** [comment]
你那边有需要展示验证码图片不，如果不需要我可以加个选项不在浏览器端显示图片，这样就不会有第二次请求了

**Comment by fastluo** [comment]
嗯会影响登录的，服务端做了xsrf处理，要利用到cookie， 
现在的情况是我要看到验证码图片，登录的时候好输入进去

**Comment by brookshi** [comment]
问个额外的问题：这个需要人工去干预，输入验证码的，做自动化怎么做呀

**Comment by fastluo** [comment]
嗯 登录一次就可以了 不用每次都输的，另外我试了下postman 没这个问题的

**Comment by brookshi** [comment]
做了下改进，在header里加上accept: image/*就会把image base64传到浏览器，这样就不会发2次请求了
大概下周一release v0.9，到时更新下就可以了

**Comment by fastluo** [comment]
好的额 感谢，可以关闭了吗？

**Comment by brookshi** [comment]
嗯
