### ISSUE TITLE
上传自定义lib或自定义data失败

### ISSUE THREAD

**Issue by zhanghang06** [brookshi/Hitchhiker#83]
![image](https://user-images.githubusercontent.com/24517540/35603755-bf91c34a-0679-11e8-89a8-7b7313b40dbc.png)

![image](https://user-images.githubusercontent.com/24517540/35603775-d7286126-0679-11e8-89c1-a7e44e2af37e.png)

**Comment by brookshi** [comment]
看起来是没有权限，你的系统是什么呢，上传的目录在api/project下，看是否有写权限

**Comment by zhanghang06** [comment]
logs显示：
![image](https://user-images.githubusercontent.com/24517540/35604065-4f534f3e-067b-11e8-84e7-fee6a9c37610.png)


maxos系统。api目录下没看到project的目录。Hitchhiker的version是461f32d6c1a6569b3fbd6d4a6b383013b3e946da

**Comment by brookshi** [comment]
哦， 不是project目录， 是global_data目录下，上传的文件都会在这个目录下，默认下面会有data 和 lib两个文件夹，是全局里，另外对于自定义的会有一个类似guid的文件夹，是以project的id命名的，只有这个project能看到，这里是用ui上传上来的

**Comment by brookshi** [comment]
看下global_data这个目录的权限

**Comment by zhanghang06** [comment]
![image](https://user-images.githubusercontent.com/24517540/35607457-220b1ad4-068f-11e8-8ffb-fdee8e10b734.png)
（1）有可操作权限的。
（2）另外我用pm2 logs hitchhiker 看log，的确像是权限有问题：
![1](https://user-images.githubusercontent.com/24517540/35607698-6f28ff1a-0690-11e8-951a-5d5f371ca1da.png)



 （3）每次pm2 kill；pm2 start ./pm2.json貌似会失败，fork太多，不知道是不是哪里有什么死循环之类的。会导致fork: Resource temporarily unavailable
![2](https://user-images.githubusercontent.com/24517540/35607702-75dea6ac-0690-11e8-99c0-ed9a07ad7f5c.png)

**Comment by brookshi** [comment]
你开了watching，因为运行时会修改一个setting文件，导致监测到改变自动重启，把watch关掉，在pm2.json里设置。
权限那个会不会是osx不支持直接mkdir多级目录呢，你手工把project的创建出来试试。
实在不行可以先把脚本文件放到global_data的lib里，这个是对所有project可见的。

**Comment by zhanghang06** [comment]
(1)我试过直接把文件放到global_data/data或者global_data/lib下，刷新页面看没有更新。试了下重启服务，pm2 kill；pm2 start ./pm2.json。然后服务就挂掉了（此时watch我是关闭的）。。。每次我都是重新执行linux_deploy.sh
(2)权限那个会不会是osx不支持直接mkdir多级目录呢，你手工把project的创建出来试试。-----这个我可以在哪里改下源代码，改成mkdir -p .../../

**Comment by brookshi** [comment]
1. 不能直接放zip文件到这个目录，解压后放进去，参考现有的Lib
2. 重启服务直接 pm2 restart hitchhiker就可以，kill后再start会挂掉我也没碰到过，上面图看起来是启成功了
3. 不用代码创建，直接人工在global_data目录下创建一个你上面图上显示的projectid的目录
![image](https://user-images.githubusercontent.com/13607728/35608608-c3b2b9be-0694-11e8-834f-9602b127f24a.png)

**Comment by zhanghang06** [comment]
提示session invalid是什么原因

**Comment by zhanghang06** [comment]
清了下cookie，在重启了服务，OK了

**Comment by brookshi** [comment]
session invalid这个可以忽略，算是个小bug，重新登录后把上一次的错误弹出来了，现在lib可以用了不

**Comment by zhanghang06** [comment]
嗯，可以用了。多谢

**Comment by brookshi** [comment]
:smile:

**Comment by zhanghang06** [comment]
不好意思，再问一下。用docker启动的服务，console.log的日志没看到在哪儿。应用目录下没有日志
![image](https://user-images.githubusercontent.com/24517540/35718945-cc40a166-0821-11e8-906c-c689a77d2c8c.png)

**Comment by zhanghang06** [comment]
再问下。自定义lib库提示：VMError: Access denied to require 'fs'
