### ISSUE TITLE
创建自定义data时，自己手动创建文件夹，然后放入多个文件。如何正确独到这些文件

### ISSUE THREAD

**Issue by zhanghang06** [brookshi/Hitchhiker#85]
现在的自定义data创建，貌似只能readFile到/data下的单个文件。我尝试在/data下面创建目录/test，然后放入多个文件(即：/data/test/1.txt    /data/test/2.txt 等)，重启docker容器。用hitchhiker.readFIle('test/1.txt')行不通。提示：test/1.txt not exists.

**Comment by brookshi** [comment]
是的，目前不支持文件上的多级目录，应该没那么多文件以至于需要分不同目录吧

**Comment by zhanghang06** [comment]
在压测的时候，感觉这种feature还是蛮常见的。将场景分类，然后一个分类下多条数据（比如文件）。然后压测的时候随机读该类case下的文件数据，防止命中服务cache之类的😆

**Comment by brookshi** [comment]
嗯，这种场景我之前预想的是可以把这类数据放到结构化的数据里面，比如excel，或者json,xml之类，读到一个文件之后可以给后面所有请求用，这个文件可能比较大，读到后存到变量里，这样只读一次，后面随机或按次序的去变量里拿想要的数据

**Comment by zhanghang06** [comment]
数据量如果不是很大，这也是一个不错的解决方法。担心数据量一大或者数据类型比较特殊，写入json或者excel的话，文件会比较大，到时候上传数据可能会出错😆

**Comment by brookshi** [comment]
嗯，数据量一般不会太大吧，局域网上传应该还好。
如果真有这种需求可以再想想方案，拆分文件或你说的分文件夹之类。
