### ISSUE TITLE
压力测试，点击‘run now’有时会没反应

### ISSUE THREAD

**Issue by zhanghang06** [brookshi/Hitchhiker#87]
压力测试，点击‘run now’有时会没反应
console控制台有输出
![image](https://user-images.githubusercontent.com/24517540/35788563-e2beb36e-0a70-11e8-8ed2-c5b9c4426308.png)

但network处没有任何请求显示。log里没看到对应的错误提示

**Comment by brookshi** [comment]
看起来你那里task积压了很多个， 是不是task没跑呢

**Comment by zhanghang06** [comment]
之前控制台输出是：
![image](https://user-images.githubusercontent.com/24517540/35788892-3bd7fa58-0a73-11e8-8358-076f94f11388.png)


于是，我重启了docker试了下，控制台打印出的data里面stressId这些有对应的值了，但是一直在run（即便是很简单的一个接口，跑一次这样）。看了下hitchhiker-node里面的log，有几次提示了error: 2018/02/05 12:42:03 client.go:83: read: invalid character '$' looking for beginning of value   。

有几次完整log是：
![image](https://user-images.githubusercontent.com/24517540/35788911-55c8e09e-0a73-11e8-8486-d7e66c236d7e.png)

**Comment by brookshi** [comment]
原来你是用go在跑呀，不用那个了，内置node已经支持压力测试了，go那个暂停了，因为对js支持不太好，很多高级特性支持不了

**Comment by zhanghang06** [comment]
我现在应该怎么整。怎么切换用nodejs发压

**Comment by brookshi** [comment]
默认应该就是node的，不知道为啥你的不是，你的版本是多少，用的docker还是安装包

**Comment by zhanghang06** [comment]
我看appconfig.json里面type=node。版本试v0.8。用的docker.


docker-compose.yml酱紫：
![image](https://user-images.githubusercontent.com/24517540/35789089-8b5c1798-0a74-11e8-8f40-5cbf2386ef6a.png)

**Comment by zhanghang06** [comment]
我之前在另一太机器上装了hitchhiker-node，然后连到了hitchhiker-api的stress port上。
我刚试了下把hitchhiker-node这个进程干掉，再重启了docker，发压正常了

**Comment by zhanghang06** [comment]
话说node的这种形式，怎么可以像hitchhiker-node那样，可以将请求分布到多台host上，然后再发送到目标服务器上呀。觉得请求分布到多台host上，并行发压这种是个亮点。不知道node的形式支不支持

**Comment by brookshi** [comment]
默认是node应该是可以的，你不开Hitchhiker-node就看不到压力点吗，那可能是node的压力进程没起来。

在分布式上会差一些，用node写的目前还没支持分布式，代码上其实是已经实现了，到时只需要在多台host再部署一套hitchhiker，把host配到主host上，压测点就会连过去

**Comment by brookshi** [comment]
其实node的分布式主要还差一个文件传输，就是上传的文件需要传到各个压力点去用。如果不关心这个的话，估计现在其实就是可用的，不过我也没测：）

**Comment by zhanghang06** [comment]
棒棒，期待node的分布式。冲着分布式这个来的😆

**Comment by brookshi** [comment]
：）

**Comment by zhanghang06** [comment]
压测的时候，提示
![image](https://user-images.githubusercontent.com/24517540/45011612-03a2cb80-b046-11e8-96a5-725e1f5b0c6f.png)

application.json里的type是node，如下：
![image](https://user-images.githubusercontent.com/24517540/45011948-baec1200-b047-11e8-9394-635f5e3bebb5.png)
