### ISSUE TITLE
测试本地服务端 API 出现的问题

### ISSUE THREAD

**Issue by dragonJACson** [brookshi/Hitchhiker#89]
我的 django 监听了 8000 端口，在 Hitchhiker 中 POST 一段数据给 `http://localhost:8000/login/` 这个 URL，结果是这样的
> Could not get any response
> Error when get data from http://localhost:8000/login/
```json
{
    "message": "connect ECONNREFUSED 127.0.0.1:8000",
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:8000\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)"
}
```
然后我写了一个 server.js 
```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
    res.send('Hello World!');
});

app.listen(8000, function () {
    console.log('Example app listening on port 8000!');
});
```
```bash
$ node server.js
Example app listening on port 8000!
```
GET `http://localhost:8000/` 得到同样的错误。
而在 Postman 中以上两个测试都是正常的，请问是哪个地方出了问题呢？

**Comment by brookshi** [comment]
你的Hitchhiker是搭在本地的吗，localhost对于Hitchhiker来说就是自己所在的机器。
如果不在同一台机器，需要做下mapping:  http://doc.hitchhiker-api.com/cn/Simple_Tutorial/Create_Project.html

**Comment by dragonJACson** [comment]
是搭在本地的，和 django 运行在同一台机器上

**Comment by brookshi** [comment]
用docker的吗

**Comment by dragonJACson** [comment]
对的，用 docker 搭的 Hitchhiker

**Comment by brookshi** [comment]
嗯，localhost对于docker container来说不是host的ip，参考： https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container/31328031#31328031

**Comment by dragonJACson** [comment]
好的，问题解决了，感谢作者解答

**Comment by brookshi** [comment]
不客气：）
