### ISSUE TITLE
响应结果乱码

### ISSUE THREAD

**Issue by wchee** [brookshi/Hitchhiker#90]
数据库是 utf8
乱码如下图
![image](https://user-images.githubusercontent.com/12848296/35901738-18ff5854-0c13-11e8-9d79-f06d593b68cd.png)

**Comment by wchee** [comment]
数据库截图
![image](https://user-images.githubusercontent.com/12848296/35901865-da8fd39a-0c13-11e8-8899-085bbeafd8f8.png)

**Comment by brookshi** [comment]
是不是你加了zip的header呢

**Comment by wchee** [comment]
@brookshi  谢谢，请求头设置好 Accept-Encoding 就好了，不过因为所有的接口都开了 gzip，能通过设置 hitchhiker 的一些配置解析压缩的内容吗？

**Comment by brookshi** [comment]
哦， 原来服务器默认开的gzip，目前没有这种全局设置，header左边有个星星可以收藏，会比较方便使用这种头。不过后面有打算加上这种全局设置，在我的task.todo里有记。
那就以这个issue为需求吧，我会实现一个folder级和collection级的通用设置request其本信息的地方

**Comment by brookshi** [comment]
要不你还是再提个issue做这需求，这个title毕竟关系不大

**Comment by wchee** [comment]
@brookshi  好的
