### ISSUE TITLE
firefox 切换request 页到另一request并不会主动刷新 request内容

### ISSUE THREAD

**Issue by Archer456** [brookshi/Hitchhiker#91]
![image](https://user-images.githubusercontent.com/18392901/35902137-fb4a5bfe-0c14-11e8-9f2f-067167425686.png)

如图从environment 切换到H5注册-密码非法字符  该页，内容区仍旧是environment 的，
请做下页面切换 内容区主动刷新

**Comment by Archer456** [comment]
另外 执行send 或其他页面切换操作  也不主动刷新当前页面。。。。。

**Comment by brookshi** [comment]
图上当前标签显示的是environment呀， 是不是卡住了，F12看下console

**Comment by Archer456** [comment]
回  绝对不是卡住了 ，  很明显的效果，    怎么切tab  始终都是上一次的tab内容    刷新F5 也亦然。  包括左侧那些功能大类目的切换...  取不回新内容。  怎么看 服务的执行日志？

**Comment by brookshi** [comment]
服务的日志在build/logs目录下，或者pm2 logs，但这个现象不像是服务端问题，有F12看下不

**Comment by Archer456** [comment]
有内容，试下 sudo docker ps，看容器是否有在运行，有的话就sudo docker exec -it 容器id bash，进到容器里面，再运行 pm2 status 看看是否在运行

我看issue  学习了  不好意思  docker不熟

**Comment by brookshi** [comment]
标个bug，下版本改进：当header是application/x-www-form-urlencoded时应该处理Body不符合格式时的错误
