### ISSUE TITLE
这个系统不支持中文吗？

### ISSUE THREAD

**Issue by caopengfei** [brookshi/Hitchhiker#92]
当填入的数据时中文时，数据同步会失败，而且所有的功能好像都不能用了，报错很多

**Comment by brookshi** [comment]
数据库需要是utf8，有没有设置这个呢

**Comment by brookshi** [comment]
fixed, refer to https://devops.stackexchange.com/questions/1960/unable-to-mount-docker-folder-into-host-using-docker-compose
