### ISSUE TITLE
hitchhiker能否直接require一些自带的js库

### ISSUE THREAD

**Issue by zhanghang06** [brookshi/Hitchhiker#98]
nodejs自带的一些库，如fs,path之类的库
能否直接require('fs')
我试了下，提示没权限
![image](https://user-images.githubusercontent.com/24517540/35969517-13f3ae2e-0d02-11e8-922a-ef59e6313955.png)

**Comment by brookshi** [comment]
不能，因为这样会完全暴露服务器给脚本，还是通过上传脚本来使用，后期打算加上权限控制，这样服务器安全性要好些。如果你想用fs可以下载一个fs-extra库上传上去
